/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with a refresh token
         * @description Exchanges the Pixiv OAuth refresh token for a short-lived access
         *     token and persists it server-side; subsequent authenticated
         *     endpoints reuse that stored session.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current session
         * @description Clears the persisted tokens and removes the on-disk state file. Idempotent.
         */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current auth status */
        get: operations["GetAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List download jobs
         * @description Newest first.
         */
        get: operations["ListDownloads"];
        put?: never;
        /**
         * Submit a download job
         * @description Resolves the illust on Pixiv, builds one task per page (or one
         *     per ugoira zip), enqueues the work, and returns the Job. The
         *     response is `202 Accepted`; the client follows progress via
         *     the `download` topic on `GET /events`.
         */
        post: operations["SubmitDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a download job */
        get: operations["GetDownload"];
        put?: never;
        post?: never;
        /**
         * Remove a download job from history
         * @description Deletes a terminal job (completed / failed / cancelled) from the
         *     store. Returns `409` if the job is still running — the client
         *     must `POST /downloads/{id}/cancel` first. When `purgeFiles=true`,
         *     already-downloaded files belonging to completed tasks are also
         *     removed from disk.
         */
        delete: operations["RemoveDownload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running download job
         * @description Cancels every non-terminal task in the job. Returns `409` if the job is already in a terminal state.
         */
        post: operations["CancelDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to the event stream
         * @description Long-lived `text/event-stream` connection. Events are typed
         *     envelopes `{id, ts, topic, type, data}` emitted by internal
         *     subsystems (downloads, auth, system). The client may filter
         *     topics via the `topics` query parameter; if omitted, every
         *     topic is delivered.
         *
         *     Reconnect behaviour follows the standard SSE semantics. If the
         *     client sends a `Last-Event-ID` header and the ring buffer
         *     still holds newer events, the server replays them before
         *     resuming live delivery. If the ID has been evicted, the server
         *     first sends a single `system.resync` event so the client
         *     knows to re-fetch authoritative state via the REST endpoints.
         */
        get: operations["GetEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List illusts from followed users */
        get: operations["ListFollowingIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ranked illusts */
        get: operations["ListRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recommended illusts */
        get: operations["ListRecommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get illust detail */
        get: operations["GetIllust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's bookmark detail for an illust */
        get: operations["GetBookmarkDetail"];
        /** Bookmark an illust */
        put: operations["AddBookmark"];
        post?: never;
        /** Remove an illust bookmark */
        delete: operations["DeleteBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}/ugoira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ugoira metadata
         * @description Returns the frame-timing manifest and the zip URL packaging
         *     each frame. Used by clients to render Pixiv's animated
         *     illustrations.
         */
        get: operations["GetUgoiraMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/illusts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search illusts
         * @description Matches by keyword or tag; see `search_target` for matching mode and `sort` for ordering.
         */
        get: operations["SearchIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users
         * @description Matches Pixiv display name or account.
         */
        get: operations["SearchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's profile detail */
        get: operations["GetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a user's bookmarks
         * @description Cursor-paginated by `max_bookmark_id`. Pass
         *     `next_max_bookmark_id` from the previous response as the next
         *     cursor.
         */
        get: operations["ListUserBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Follow a user */
        put: operations["AddFollow"];
        post?: never;
        /** Unfollow a user */
        delete: operations["DeleteFollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users followed by a user */
        get: operations["ListUserFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/illusts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List illusts by a user */
        get: operations["ListUserIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthStatus: {
            authenticated: boolean;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int64 */
            user_id?: number | null;
            user_name?: string | null;
        };
        BookmarkDetail: {
            is_bookmarked: boolean;
            restrict: components["schemas"]["Restrict"];
        };
        BookmarkRequest: {
            restrict?: components["schemas"]["Restrict"];
        };
        /**
         * @description Pixiv artwork type the job was created for.
         * @enum {string}
         */
        DownloadIllustType: "illust" | "manga" | "ugoira";
        DownloadJob: {
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: int64 */
            illust_id: number;
            illust_type: components["schemas"]["DownloadIllustType"];
            status: components["schemas"]["DownloadStatus"];
            tasks: components["schemas"]["DownloadTask"][];
            title?: string;
            /** Format: date-time */
            updated_at: string;
        };
        DownloadJobList: {
            jobs: components["schemas"]["DownloadJob"][];
        };
        /**
         * @description Lifecycle state of a download job or task.
         * @enum {string}
         */
        DownloadStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        DownloadTask: {
            /** Format: int64 */
            downloaded_bytes: number;
            error?: string | null;
            /** @description Target path on disk. */
            file_path: string;
            /** Format: date-time */
            finished_at?: string | null;
            id: string;
            job_id: string;
            /**
             * Format: int64
             * @description Content-Length, or -1 if unknown.
             */
            size_bytes: number;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["DownloadStatus"];
            /** @description Final request URL (after pximg mirror rewrite). */
            url: string;
        };
        Error: {
            /**
             * @description Machine-readable error code.
             * @example unauthenticated
             */
            code: string;
            /** @description Optional additional context (e.g., upstream body). */
            detail?: string;
            /** @description Human-readable error message. */
            message: string;
        };
        FollowRequest: {
            restrict?: components["schemas"]["Restrict"];
        };
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        /** @description Pixiv illustration metadata. Shape mirrors pixivgo.IllustrationInfo. */
        Illust: {
            caption: string;
            create_date: string;
            /** Format: int64 */
            height: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            illust_ai_type: number;
            /** Format: int64 */
            illust_book_style: number;
            image_urls: components["schemas"]["ImageUrls"];
            is_bookmarked: boolean;
            is_muted: boolean;
            meta_pages: components["schemas"]["MetaPage"][];
            meta_single_page: components["schemas"]["MetaSinglePage"];
            /** Format: int64 */
            page_count: number;
            /** Format: int64 */
            restrict: number;
            restriction_attributes: string[];
            /** Format: int64 */
            sanity_level: number;
            series: components["schemas"]["Series"] | null;
            tags: components["schemas"]["IllustrationTag"][];
            title: string;
            tools: string[];
            /** Format: int64 */
            total_bookmarks: number;
            /** Format: int64 */
            total_comments?: number;
            /** Format: int64 */
            total_view: number;
            type: string;
            user: components["schemas"]["User"];
            visible: boolean;
            /** Format: int64 */
            width: number;
            /** Format: int64 */
            x_restrict: number;
        };
        /** @description Wrapper for a single illust detail. Mirrors pixivgo.IllustDetailResponse. */
        IllustDetailResponse: {
            illust: components["schemas"]["Illust"];
        };
        IllustPage: {
            illusts: components["schemas"]["Illust"][];
            /**
             * Format: int64
             * @description Set only by `/users/{id}/bookmarks`; pass back as `max_bookmark_id`.
             */
            next_max_bookmark_id?: number | null;
            /**
             * Format: int64
             * @description Next offset to pass back, or null if no further page.
             */
            next_offset?: number | null;
        };
        /** @enum {string} */
        IllustType: "illust" | "manga";
        IllustrationTag: {
            name: string;
            translated_name: string | null;
        };
        ImageUrls: {
            large: string;
            medium: string;
            square_medium: string;
        };
        LoginRequest: {
            /** @description Long-lived Pixiv OAuth refresh token. See README for how to obtain. */
            refresh_token: string;
        };
        MetaPage: {
            image_urls: components["schemas"]["ImageUrls"];
        };
        MetaSinglePage: {
            original_image_url?: string;
        };
        /** @description Pixiv novel metadata. Shape mirrors pixivgo.NovelInfo. */
        Novel: {
            caption: string;
            /** Format: int64 */
            comment_access_control?: number;
            create_date: string;
            /** Format: int64 */
            id: number;
            image_urls: components["schemas"]["ImageUrls"];
            is_bookmarked: boolean;
            is_muted: boolean;
            is_mypixiv_only: boolean;
            is_original: boolean;
            is_x_restricted: boolean;
            /** Format: int64 */
            novel_ai_type: number;
            /** Format: int64 */
            page_count: number;
            /** Format: int64 */
            restrict: number;
            series: components["schemas"]["Series"] | null;
            tags: components["schemas"]["NovelTag"][];
            /** Format: int64 */
            text_length: number;
            title: string;
            /** Format: int64 */
            total_bookmarks: number;
            /** Format: int64 */
            total_comments: number;
            /** Format: int64 */
            total_view: number;
            user: components["schemas"]["User"];
            visible: boolean;
            /** Format: int64 */
            x_restrict: number;
        };
        NovelTag: {
            added_by_uploaded_user: boolean;
            name: string;
            translated_name: string | null;
        };
        /** @description Pixiv user profile. Shape mirrors pixivgo.Profile. */
        Profile: {
            /** Format: int64 */
            address_id: number;
            background_image_url: string;
            birth: string;
            birth_day: string;
            /** Format: int64 */
            birth_year: number;
            country_code: string;
            gender: string;
            is_premium: boolean;
            is_using_custom_profile_image: boolean;
            job: string;
            /** Format: int64 */
            job_id: number;
            pawoo_url: string | null;
            region: string;
            /** Format: int64 */
            total_follow_users: number;
            /** Format: int64 */
            total_illust_bookmarks_public: number;
            /** Format: int64 */
            total_illust_series: number;
            /** Format: int64 */
            total_illusts: number;
            /** Format: int64 */
            total_manga: number;
            /** Format: int64 */
            total_mypixiv_users: number;
            /** Format: int64 */
            total_novel_series: number;
            /** Format: int64 */
            total_novels: number;
            twitter_account: string;
            twitter_url: string | null;
            webpage: string | null;
        };
        ProfileImageUrls: {
            medium: string;
        };
        /** @description Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity. */
        ProfilePublicity: {
            birth_day: string;
            birth_year: string;
            gender: string;
            job: string;
            pawoo: boolean;
            region: string;
        };
        /** @enum {string} */
        RankingMode:
            | "day"
            | "week"
            | "month"
            | "day_male"
            | "day_female"
            | "week_original"
            | "week_rookie"
            | "day_manga"
            | "day_r18"
            | "day_male_r18"
            | "day_female_r18"
            | "week_r18"
            | "week_r18g";
        /**
         * @default public
         * @enum {string}
         */
        Restrict: "public" | "private";
        /**
         * @default date_desc
         * @enum {string}
         */
        SearchSort: "date_desc" | "date_asc" | "popular_desc";
        /**
         * @default partial_match_for_tags
         * @enum {string}
         */
        SearchTarget: "partial_match_for_tags" | "exact_match_for_tags" | "title_and_caption" | "keyword";
        /** @description Pixiv returns `{}` instead of `null` for empty series; in that case `id` is 0. */
        Series: {
            /** Format: int64 */
            id: number;
            title: string;
        };
        SubmitDownloadRequest: {
            /**
             * Format: int64
             * @description Pixiv illustration ID.
             */
            illust_id: number;
        };
        UgoiraFrame: {
            /** Format: int64 */
            delay: number;
            file: string;
        };
        UgoiraMetadata: {
            frames: components["schemas"]["UgoiraFrame"][];
            zip_urls: components["schemas"]["UgoiraZipUrls"];
        };
        /** @description Ugoira (animated illust) metadata. Mirrors pixivgo.UgoiraMetadataResponse. */
        UgoiraMetadataResponse: {
            ugoira_metadata: components["schemas"]["UgoiraMetadata"];
        };
        UgoiraZipUrls: {
            medium: string;
        };
        /** @description Pixiv user summary. Shape mirrors pixivgo.UserInfo. */
        User: {
            account: string;
            comment?: string;
            /** Format: int64 */
            id: number;
            is_accept_request?: boolean;
            is_access_blocking_user?: boolean;
            is_followed: boolean | null;
            name: string;
            profile_image_urls: components["schemas"]["ProfileImageUrls"];
        };
        UserDetailPage: {
            profile: components["schemas"]["Profile"];
            profile_publicity: components["schemas"]["ProfilePublicity"];
            user: components["schemas"]["User"];
            workspace: components["schemas"]["Workspace"];
        };
        UserIllustsPage: {
            illusts: components["schemas"]["Illust"][];
            /** Format: int64 */
            next_offset?: number | null;
            user: components["schemas"]["User"];
        };
        /** @description User + a few sample illusts. Shape mirrors pixivgo.UserPreview. */
        UserPreview: {
            illusts: components["schemas"]["Illust"][];
            is_muted: boolean;
            novels: components["schemas"]["Novel"][];
            user: components["schemas"]["User"];
        };
        UserPreviewPage: {
            /** Format: int64 */
            next_offset?: number | null;
            user_previews: components["schemas"]["UserPreview"][];
        };
        /** @description Pixiv workspace info. Shape mirrors pixivgo.Workspace. */
        Workspace: {
            chair: string;
            comment: string;
            desk: string;
            desktop: string;
            monitor: string;
            mouse: string;
            music: string;
            pc: string;
            printer: string;
            scanner: string;
            tablet: string;
            tool: string;
            workspace_image_url: string | null;
        };
    };
    responses: {
        /** @description Invalid parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Action succeeded; no body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Resource not found on Pixiv. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid Pixiv session. Call `POST /auth/login` first. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Pixiv upstream returned an unexpected error. */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Download job identifier returned by `POST /downloads`. */
        DownloadIdPath: string;
        /** @description Pixiv illustration ID. */
        IllustIdPath: number;
        /** @description Illust type filter; both are returned when omitted (where supported). */
        IllustTypeQuery: components["schemas"]["IllustType"];
        /** @description Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response. */
        MaxBookmarkIdQuery: number;
        /** @description Offset for offset-paginated list endpoints. */
        OffsetQuery: number;
        /** @description Visibility scope (public or private). */
        RestrictQuery: components["schemas"]["Restrict"];
        /** @description Pixiv user ID. */
        UserIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. The access token is stored server-side. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
        };
    };
    GetAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current auth status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    ListDownloads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJobList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    SubmitDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitDownloadRequest"];
            };
        };
        responses: {
            /** @description Job accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    GetDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJob"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    RemoveDownload: {
        parameters: {
            query?: {
                /** @description When `true`, also delete the downloaded files from disk. */
                purgeFiles?: boolean;
            };
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description Job is still running — cancel it before removing. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CancelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description Job is already in a terminal state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetEvents: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated topic filter (e.g. `download,system`).
                 *     Omit for all topics.
                 */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    ListFollowingIllusts: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Following feed page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    ListRanking: {
        parameters: {
            query?: {
                mode?: components["schemas"]["RankingMode"];
                /** @description Ranking date in `YYYY-MM-DD`. Omit for the latest. */
                date?: string;
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    ListRecommended: {
        parameters: {
            query?: {
                /** @description Illust type filter; both are returned when omitted (where supported). */
                type?: components["parameters"]["IllustTypeQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendation page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    GetIllust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Illustration detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustDetailResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    GetBookmarkDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    AddBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookmarkRequest"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    DeleteBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    GetUgoiraMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ugoira metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UgoiraMetadataResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    SearchIllusts: {
        parameters: {
            query: {
                word: string;
                search_target?: components["schemas"]["SearchTarget"];
                sort?: components["schemas"]["SearchSort"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    SearchUsers: {
        parameters: {
            query: {
                word: string;
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreviewPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    ListUserBookmarks: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response. */
                max_bookmark_id?: components["parameters"]["MaxBookmarkIdQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarks page. `next_max_bookmark_id` is set when another page exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    AddFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    DeleteFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    ListUserFollowing: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Following page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreviewPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    ListUserIllusts: {
        parameters: {
            query?: {
                /** @description Illust type filter; both are returned when omitted (where supported). */
                type?: components["parameters"]["IllustTypeQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User illusts page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIllustsPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
}
