/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with a refresh token
         * @description Exchanges the Pixiv OAuth refresh token for a short-lived access
         *     token and persists it server-side; subsequent authenticated
         *     endpoints reuse that stored session.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current session
         * @description Clears the persisted tokens and removes the on-disk state file. Idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current auth status */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a browser-driven Pixiv OAuth (PKCE) login
         * @description Generates a server-side PKCE verifier and returns the hosted Pixiv
         *     login URL the client should open in a popup. The server keeps the
         *     verifier indexed by `state`; the client posts `state` + the
         *     authorisation `code` back to `/auth/oauth/exchange` to complete login.
         *     Issued states expire after ~10 minutes and are single-use.
         */
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a browser-driven Pixiv OAuth login
         * @description Trades the Pixiv authorisation code (returned in the callback URL of
         *     the hosted login page) for a refresh + access token using the PKCE
         *     verifier the server stored under `state`. `code` may be the bare
         *     code, or the full callback URL — the server extracts `?code=…`.
         *     Persists the resulting tokens just like `/auth/login`.
         */
        post: operations["exchangeOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ranked illusts */
        get: operations["listRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recommended illusts */
        get: operations["listRecommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List illusts from followed users */
        get: operations["listFollowingIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get illust detail */
        get: operations["getIllust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}/ugoira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ugoira metadata
         * @description Returns the frame-timing manifest and the zip URL packaging
         *     each frame. Used by clients to render Pixiv's animated
         *     illustrations.
         */
        get: operations["getUgoiraMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/illusts/{id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's bookmark detail for an illust */
        get: operations["getBookmarkDetail"];
        /** Bookmark an illust */
        put: operations["addBookmark"];
        post?: never;
        /** Remove an illust bookmark */
        delete: operations["deleteBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's profile detail */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/illusts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List illusts by a user */
        get: operations["listUserIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a user's bookmarks
         * @description Cursor-paginated by `max_bookmark_id`. Pass
         *     `next_max_bookmark_id` from the previous response as the next
         *     cursor.
         */
        get: operations["listUserBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users followed by a user */
        get: operations["listUserFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Follow a user */
        put: operations["addFollow"];
        post?: never;
        /** Unfollow a user */
        delete: operations["deleteFollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/illusts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search illusts
         * @description Matches by keyword or tag; see `search_target` for matching mode and `sort` for ordering.
         */
        get: operations["searchIllusts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users
         * @description Matches Pixiv display name or account.
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List download jobs (paginated)
         * @description Server-paginated list. Order is newest first. Without filters
         *     every job is returned, but `page` / `per_page` always apply.
         *     Response carries the total count plus global `active_count` /
         *     `done_count` so clients don't need a separate counts endpoint.
         */
        get: operations["listDownloads"];
        put?: never;
        /**
         * Submit a download job
         * @description Resolves the illust on Pixiv, builds one task per page (or one
         *     per ugoira zip), enqueues the work, and returns the Job. The
         *     response is `202 Accepted`; the client follows progress via
         *     the `download` topic on `GET /events`.
         */
        post: operations["submitDownload"];
        /**
         * Bulk-remove terminal download jobs from history
         * @description Deletes every job whose status is terminal and matches the optional
         *     `status` filter. Empty filter defaults to all terminal statuses.
         *     Non-terminal statuses return `400`. Files on disk are not touched.
         */
        delete: operations["clearDownloads"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a download job */
        get: operations["getDownload"];
        put?: never;
        post?: never;
        /**
         * Remove a download job from history
         * @description Deletes a terminal job (completed / failed / cancelled) from the
         *     store. The Download List is a history log: this removes the
         *     record only — already-downloaded files on disk are not touched.
         *     Returns `409` if the job is still running — the client must
         *     `POST /downloads/{id}/cancel` first. To delete files, use a file
         *     manager.
         */
        delete: operations["removeDownload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running download job
         * @description Cancels every non-terminal task in the job. Returns `409` if the job is already in a terminal state.
         */
        post: operations["cancelDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to the event stream
         * @description Long-lived `text/event-stream` connection. Events are typed
         *     envelopes `{id, ts, topic, type, data}` emitted by internal
         *     subsystems (downloads, auth, system). The client may filter
         *     topics via the `topics` query parameter; if omitted, every
         *     topic is delivered.
         *
         *     Reconnect behaviour follows the standard SSE semantics. If the
         *     client sends a `Last-Event-ID` header and the ring buffer
         *     still holds newer events, the server replays them before
         *     resuming live delivery. If the ID has been evicted, the server
         *     first sends a single `system.resync` event so the client
         *     knows to re-fetch authoritative state via the REST endpoints.
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        Error: {
            /**
             * @description Machine-readable error code.
             * @example unauthenticated
             */
            code: string;
            /** @description Human-readable error message. */
            message: string;
            /** @description Optional additional context (e.g., upstream body). */
            detail?: string;
        };
        /**
         * @default public
         * @enum {string}
         */
        Restrict: "public" | "private";
        /** @enum {string} */
        IllustType: "illust" | "manga";
        /**
         * @description Pixiv `filter` knob — controls iOS-app-style content gating.
         *     `for_ios` applies Pixiv's iOS-client policy filter; `none` disables
         *     it. Named `client_mode` here to avoid collision with the generic
         *     notion of "filtering".
         * @enum {string}
         */
        ClientMode: "for_ios" | "none";
        /** @enum {string} */
        SearchDuration: "within_last_day" | "within_last_week" | "within_last_month";
        /** @enum {string} */
        RankingMode: "day" | "week" | "month" | "day_male" | "day_female" | "week_original" | "week_rookie" | "day_manga" | "day_r18" | "day_male_r18" | "day_female_r18" | "week_r18" | "week_r18g";
        /**
         * @default partial_match_for_tags
         * @enum {string}
         */
        SearchTarget: "partial_match_for_tags" | "exact_match_for_tags" | "title_and_caption" | "keyword";
        /**
         * @default date_desc
         * @enum {string}
         */
        SearchSort: "date_desc" | "date_asc" | "popular_desc";
        LoginRequest: {
            /** @description Long-lived Pixiv OAuth refresh token. See README for how to obtain. */
            refresh_token: string;
        };
        OAuthStartResponse: {
            /**
             * @description Opaque handle the client must echo back to `/auth/oauth/exchange`.
             *     The server uses it to look up the matching PKCE verifier.
             */
            state: string;
            /**
             * @description Pixiv-hosted login URL the client should open in a popup. After
             *     the user authenticates Pixiv redirects to a fixed callback URL
             *     that carries `?code=…`; the user pastes that URL (or just the
             *     code) back into the client.
             */
            login_url: string;
        };
        OAuthExchangeRequest: {
            /** @description The `state` returned by `/auth/oauth/start`. */
            state: string;
            /**
             * @description Either the bare authorisation `code` Pixiv emitted, or the full
             *     callback URL the user pasted (the server extracts `?code=…`).
             */
            code: string;
        };
        AuthStatus: {
            authenticated: boolean;
            /** Format: int64 */
            user_id?: number | null;
            user_name?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        BookmarkRequest: {
            restrict?: components["schemas"]["Restrict"];
        };
        BookmarkDetail: {
            is_bookmarked: boolean;
            restrict: components["schemas"]["Restrict"];
        };
        FollowRequest: {
            restrict?: components["schemas"]["Restrict"];
        };
        /** @description Pixiv illustration metadata. Shape mirrors pixivgo.IllustrationInfo. */
        Illust: {
            /** Format: int64 */
            id: number;
            title: string;
            type: string;
            image_urls: components["schemas"]["ImageUrls"];
            caption: string;
            /** Format: int64 */
            restrict: number;
            user: components["schemas"]["User"];
            tags: components["schemas"]["IllustrationTag"][];
            tools: string[];
            create_date: string;
            /** Format: int64 */
            page_count: number;
            /** Format: int64 */
            width: number;
            /** Format: int64 */
            height: number;
            /** Format: int64 */
            sanity_level: number;
            /** Format: int64 */
            x_restrict: number;
            series: components["schemas"]["Series"] | null;
            meta_single_page: components["schemas"]["MetaSinglePage"];
            meta_pages: components["schemas"]["MetaPage"][];
            /** Format: int64 */
            total_view: number;
            /** Format: int64 */
            total_bookmarks: number;
            is_bookmarked: boolean;
            visible: boolean;
            is_muted: boolean;
            /** Format: int64 */
            illust_ai_type: number;
            /** Format: int64 */
            illust_book_style: number;
            /** Format: int64 */
            total_comments?: number;
            restriction_attributes: string[];
        };
        /** @description Pixiv user summary. Shape mirrors pixivgo.UserInfo. */
        User: {
            /** Format: int64 */
            id: number;
            name: string;
            account: string;
            profile_image_urls: components["schemas"]["ProfileImageUrls"];
            comment?: string;
            is_followed: boolean | null;
            is_access_blocking_user?: boolean;
            is_accept_request?: boolean;
        };
        /** @description User + a few sample illusts. Shape mirrors pixivgo.UserPreview. */
        UserPreview: {
            user: components["schemas"]["User"];
            illusts: components["schemas"]["Illust"][];
            novels: components["schemas"]["Novel"][];
            is_muted: boolean;
        };
        IllustPage: {
            illusts: components["schemas"]["Illust"][];
            /**
             * Format: int64
             * @description Next offset to pass back, or null if no further page.
             */
            next_offset?: number | null;
            /**
             * Format: int64
             * @description Set only by `/users/{id}/bookmarks`; pass back as `max_bookmark_id`.
             */
            next_max_bookmark_id?: number | null;
        };
        UserIllustsPage: {
            user: components["schemas"]["User"];
            illusts: components["schemas"]["Illust"][];
            /** Format: int64 */
            next_offset?: number | null;
        };
        UserDetailPage: {
            user: components["schemas"]["User"];
            profile: components["schemas"]["Profile"];
            profile_publicity: components["schemas"]["ProfilePublicity"];
            workspace: components["schemas"]["Workspace"];
        };
        /** @description Pixiv user profile. Shape mirrors pixivgo.Profile. */
        Profile: {
            webpage: string | null;
            gender: string;
            birth: string;
            birth_day: string;
            /** Format: int64 */
            birth_year: number;
            region: string;
            /** Format: int64 */
            address_id: number;
            country_code: string;
            job: string;
            /** Format: int64 */
            job_id: number;
            /** Format: int64 */
            total_follow_users: number;
            /** Format: int64 */
            total_mypixiv_users: number;
            /** Format: int64 */
            total_illusts: number;
            /** Format: int64 */
            total_manga: number;
            /** Format: int64 */
            total_novels: number;
            /** Format: int64 */
            total_illust_bookmarks_public: number;
            /** Format: int64 */
            total_illust_series: number;
            /** Format: int64 */
            total_novel_series: number;
            background_image_url: string;
            twitter_account: string;
            twitter_url: string | null;
            pawoo_url: string | null;
            is_premium: boolean;
            is_using_custom_profile_image: boolean;
        };
        /** @description Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity. */
        ProfilePublicity: {
            gender: string;
            region: string;
            birth_day: string;
            birth_year: string;
            job: string;
            pawoo: boolean;
        };
        /** @description Pixiv workspace info. Shape mirrors pixivgo.Workspace. */
        Workspace: {
            pc: string;
            monitor: string;
            tool: string;
            scanner: string;
            tablet: string;
            mouse: string;
            printer: string;
            desktop: string;
            music: string;
            desk: string;
            chair: string;
            comment: string;
            workspace_image_url: string | null;
        };
        UserPreviewPage: {
            user_previews: components["schemas"]["UserPreview"][];
            /** Format: int64 */
            next_offset?: number | null;
        };
        /** @description Wrapper for a single illust detail. Mirrors pixivgo.IllustDetailResponse. */
        IllustDetailResponse: {
            illust: components["schemas"]["Illust"];
        };
        /** @description Ugoira (animated illust) metadata. Mirrors pixivgo.UgoiraMetadataResponse. */
        UgoiraMetadataResponse: {
            ugoira_metadata: components["schemas"]["UgoiraMetadata"];
        };
        ProfileImageUrls: {
            medium: string;
        };
        ImageUrls: {
            square_medium: string;
            medium: string;
            large: string;
        };
        IllustrationTag: {
            name: string;
            translated_name: string | null;
        };
        /** @description Pixiv returns `{}` instead of `null` for empty series; in that case `id` is 0. */
        Series: {
            /** Format: int64 */
            id: number;
            title: string;
        };
        MetaSinglePage: {
            original_image_url?: string;
        };
        MetaPage: {
            image_urls: components["schemas"]["ImageUrls"];
        };
        /** @description Pixiv novel metadata. Shape mirrors pixivgo.NovelInfo. */
        Novel: {
            /** Format: int64 */
            id: number;
            title: string;
            caption: string;
            /** Format: int64 */
            restrict: number;
            /** Format: int64 */
            x_restrict: number;
            is_original: boolean;
            image_urls: components["schemas"]["ImageUrls"];
            create_date: string;
            tags: components["schemas"]["NovelTag"][];
            /** Format: int64 */
            page_count: number;
            /** Format: int64 */
            text_length: number;
            user: components["schemas"]["User"];
            series: components["schemas"]["Series"] | null;
            is_bookmarked: boolean;
            /** Format: int64 */
            total_bookmarks: number;
            /** Format: int64 */
            total_view: number;
            visible: boolean;
            /** Format: int64 */
            total_comments: number;
            is_muted: boolean;
            is_mypixiv_only: boolean;
            is_x_restricted: boolean;
            /** Format: int64 */
            novel_ai_type: number;
            /** Format: int64 */
            comment_access_control?: number;
        };
        NovelTag: {
            name: string;
            translated_name: string | null;
            added_by_uploaded_user: boolean;
        };
        UgoiraMetadata: {
            zip_urls: components["schemas"]["UgoiraZipUrls"];
            frames: components["schemas"]["UgoiraFrame"][];
        };
        UgoiraZipUrls: {
            medium: string;
        };
        UgoiraFrame: {
            file: string;
            /** Format: int64 */
            delay: number;
        };
        /**
         * @description Lifecycle state of a download job or task.
         * @enum {string}
         */
        DownloadStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /**
         * @description Pixiv artwork type the job was created for.
         * @enum {string}
         */
        DownloadIllustType: "illust" | "manga" | "ugoira";
        DownloadTask: {
            id: string;
            job_id: string;
            /** @description Final request URL (after pximg mirror rewrite). */
            url: string;
            /** @description Target path on disk. */
            file_path: string;
            status: components["schemas"]["DownloadStatus"];
            /**
             * Format: int64
             * @description Content-Length, or -1 if unknown.
             */
            size_bytes: number;
            /** Format: int64 */
            downloaded_bytes: number;
            error?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        DownloadJob: {
            id: string;
            /** Format: int64 */
            illust_id: number;
            illust_type: components["schemas"]["DownloadIllustType"];
            title?: string;
            /** @description Thumbnail (square_medium → medium → large). Absent on jobs persisted before this field existed. */
            preview_url?: string;
            status: components["schemas"]["DownloadStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            tasks: components["schemas"]["DownloadTask"][];
        };
        DownloadJobList: {
            jobs: components["schemas"]["DownloadJob"][];
            /** @description Total jobs matching the filter (status + updated_since). */
            total: number;
            /** @description Echo of the requested 1-based page index after clamping. */
            page: number;
            /** @description Echo of the effective page size after clamping. */
            per_page: number;
            /**
             * @description Global count of `queued` + `running` jobs (independent of filter).
             *     Drives the sidebar badge.
             */
            active_count: number;
            /** @description Global count of `completed` jobs (independent of filter). */
            done_count: number;
        };
        SubmitDownloadRequest: {
            /**
             * Format: int64
             * @description Pixiv illustration ID.
             */
            illust_id: number;
        };
        ClearDownloadsResponse: {
            /** @description Number of jobs deleted from history. */
            removed: number;
        };
    };
    responses: {
        /** @description Action succeeded; no body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description No valid Pixiv session. Call `POST /auth/login` first. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found on Pixiv. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Pixiv upstream returned an unexpected error. */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Pixiv illustration ID. */
        IllustIdPath: number;
        /** @description Pixiv user ID. */
        UserIdPath: number;
        /** @description Offset for offset-paginated list endpoints. */
        OffsetQuery: number;
        /** @description Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response. */
        MaxBookmarkIdQuery: number;
        /** @description Visibility scope (public or private). */
        RestrictQuery: components["schemas"]["Restrict"];
        /** @description Illust type filter; both are returned when omitted (where supported). */
        IllustTypeQuery: components["schemas"]["IllustType"];
        /**
         * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
         *     to apply the same policy filter as the official iOS client;
         *     pass `none` to disable.
         */
        ClientModeQuery: components["schemas"]["ClientMode"];
        /** @description Time-window filter for search results. */
        DurationQuery: components["schemas"]["SearchDuration"];
        /**
         * @description When true, exclude AI-generated works from search results
         *     (Pixiv `search_ai_type=1`). Omit or set false to include them.
         */
        ExcludeAiQuery: boolean;
        /** @description Restrict bookmarks to those tagged with this exact tag name. */
        BookmarkTagQuery: string;
        /**
         * @description When false, omit the daily-ranking section Pixiv injects into the
         *     recommended feed. Omit to keep Pixiv's default behaviour.
         */
        IncludeRankingIllustsQuery: boolean;
        /** @description Download job identifier returned by `POST /downloads`. */
        DownloadIdPath: string;
        /**
         * @description Comma-separated subset of `DownloadStatus` to include. Omit for no
         *     filter. Example: `queued,running`.
         * @example queued,running
         */
        DownloadStatusListQuery: string;
        /** @description 1-based page index. */
        DownloadPageQuery: number;
        /** @description Items per page; clamped to `[1, 100]`. */
        DownloadPerPageQuery: number;
        /**
         * @description RFC3339 timestamp. Only jobs with `updated_at >= updated_since`
         *     are returned. Used by the frontend to load the recent-tracked
         *     window without scanning the whole history.
         */
        DownloadUpdatedSinceQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. The access token is stored server-side. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current auth status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login flow started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
        };
    };
    exchangeOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthExchangeRequest"];
            };
        };
        responses: {
            /** @description Authenticated. The access token is stored server-side. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    listRanking: {
        parameters: {
            query?: {
                mode?: components["schemas"]["RankingMode"];
                /** @description Ranking date in `YYYY-MM-DD`. Omit for the latest. */
                date?: string;
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    listRecommended: {
        parameters: {
            query?: {
                /** @description Illust type filter; both are returned when omitted (where supported). */
                type?: components["parameters"]["IllustTypeQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
                /**
                 * @description When false, omit the daily-ranking section Pixiv injects into the
                 *     recommended feed. Omit to keep Pixiv's default behaviour.
                 */
                include_ranking_illusts?: components["parameters"]["IncludeRankingIllustsQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendation page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    listFollowingIllusts: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Following feed page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    getIllust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Illustration detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustDetailResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    getUgoiraMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ugoira metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UgoiraMetadataResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    getBookmarkDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookmarkRequest"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    deleteBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv illustration ID. */
                id: components["parameters"]["IllustIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    getUser: {
        parameters: {
            query?: {
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    listUserIllusts: {
        parameters: {
            query?: {
                /** @description Illust type filter; both are returned when omitted (where supported). */
                type?: components["parameters"]["IllustTypeQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User illusts page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIllustsPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    listUserBookmarks: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response. */
                max_bookmark_id?: components["parameters"]["MaxBookmarkIdQuery"];
                /** @description Restrict bookmarks to those tagged with this exact tag name. */
                tag?: components["parameters"]["BookmarkTagQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarks page. `next_max_bookmark_id` is set when another page exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    listUserFollowing: {
        parameters: {
            query?: {
                /** @description Visibility scope (public or private). */
                restrict?: components["parameters"]["RestrictQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
            };
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Following page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreviewPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    addFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    deleteFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pixiv user ID. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    searchIllusts: {
        parameters: {
            query: {
                word: string;
                search_target?: components["schemas"]["SearchTarget"];
                sort?: components["schemas"]["SearchSort"];
                /** @description Lower bound `YYYY-MM-DD` for creation date. */
                start_date?: string;
                /** @description Upper bound `YYYY-MM-DD` for creation date. */
                end_date?: string;
                /** @description Time-window filter for search results. */
                duration?: components["parameters"]["DurationQuery"];
                /**
                 * @description When true, exclude AI-generated works from search results
                 *     (Pixiv `search_ai_type=1`). Omit or set false to include them.
                 */
                exclude_ai?: components["parameters"]["ExcludeAiQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IllustPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                word: string;
                sort?: components["schemas"]["SearchSort"];
                /** @description Time-window filter for search results. */
                duration?: components["parameters"]["DurationQuery"];
                /** @description Offset for offset-paginated list endpoints. */
                offset?: components["parameters"]["OffsetQuery"];
                /**
                 * @description Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
                 *     to apply the same policy filter as the official iOS client;
                 *     pass `none` to disable.
                 */
                client_mode?: components["parameters"]["ClientModeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreviewPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["Upstream"];
        };
    };
    listDownloads: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated subset of `DownloadStatus` to include. Omit for no
                 *     filter. Example: `queued,running`.
                 * @example queued,running
                 */
                status?: components["parameters"]["DownloadStatusListQuery"];
                /** @description 1-based page index. */
                page?: components["parameters"]["DownloadPageQuery"];
                /** @description Items per page; clamped to `[1, 100]`. */
                per_page?: components["parameters"]["DownloadPerPageQuery"];
                /**
                 * @description RFC3339 timestamp. Only jobs with `updated_at >= updated_since`
                 *     are returned. Used by the frontend to load the recent-tracked
                 *     window without scanning the whole history.
                 */
                updated_since?: components["parameters"]["DownloadUpdatedSinceQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs list page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJobList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    submitDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitDownloadRequest"];
            };
        };
        responses: {
            /** @description Job accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Upstream"];
        };
    };
    clearDownloads: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated subset of `DownloadStatus` to include. Omit for no
                 *     filter. Example: `queued,running`.
                 * @example queued,running
                 */
                status?: components["parameters"]["DownloadStatusListQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removal summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearDownloadsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJob"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    removeDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description Job is still running — cancel it before removing. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Download job identifier returned by `POST /downloads`. */
                id: components["parameters"]["DownloadIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description Job is already in a terminal state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated topic filter (e.g. `download,system`).
                 *     Omit for all topics.
                 */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
