// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	pixivgo "github.com/txperl/pixivgo"
)

// Defines values for DownloadIllustType.
const (
	DownloadIllustTypeIllust DownloadIllustType = "illust"
	DownloadIllustTypeManga  DownloadIllustType = "manga"
	DownloadIllustTypeUgoira DownloadIllustType = "ugoira"
)

// Valid indicates whether the value is a known member of the DownloadIllustType enum.
func (e DownloadIllustType) Valid() bool {
	switch e {
	case DownloadIllustTypeIllust:
		return true
	case DownloadIllustTypeManga:
		return true
	case DownloadIllustTypeUgoira:
		return true
	default:
		return false
	}
}

// Defines values for DownloadStatus.
const (
	Cancelled DownloadStatus = "cancelled"
	Completed DownloadStatus = "completed"
	Failed    DownloadStatus = "failed"
	Queued    DownloadStatus = "queued"
	Running   DownloadStatus = "running"
)

// Valid indicates whether the value is a known member of the DownloadStatus enum.
func (e DownloadStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for IllustType.
const (
	IllustTypeIllust IllustType = "illust"
	IllustTypeManga  IllustType = "manga"
)

// Valid indicates whether the value is a known member of the IllustType enum.
func (e IllustType) Valid() bool {
	switch e {
	case IllustTypeIllust:
		return true
	case IllustTypeManga:
		return true
	default:
		return false
	}
}

// Defines values for RankingMode.
const (
	Day          RankingMode = "day"
	DayFemale    RankingMode = "day_female"
	DayFemaleR18 RankingMode = "day_female_r18"
	DayMale      RankingMode = "day_male"
	DayMaleR18   RankingMode = "day_male_r18"
	DayManga     RankingMode = "day_manga"
	DayR18       RankingMode = "day_r18"
	Month        RankingMode = "month"
	Week         RankingMode = "week"
	WeekOriginal RankingMode = "week_original"
	WeekR18      RankingMode = "week_r18"
	WeekR18g     RankingMode = "week_r18g"
	WeekRookie   RankingMode = "week_rookie"
)

// Valid indicates whether the value is a known member of the RankingMode enum.
func (e RankingMode) Valid() bool {
	switch e {
	case Day:
		return true
	case DayFemale:
		return true
	case DayFemaleR18:
		return true
	case DayMale:
		return true
	case DayMaleR18:
		return true
	case DayManga:
		return true
	case DayR18:
		return true
	case Month:
		return true
	case Week:
		return true
	case WeekOriginal:
		return true
	case WeekR18:
		return true
	case WeekR18g:
		return true
	case WeekRookie:
		return true
	default:
		return false
	}
}

// Defines values for Restrict.
const (
	Private Restrict = "private"
	Public  Restrict = "public"
)

// Valid indicates whether the value is a known member of the Restrict enum.
func (e Restrict) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for SearchSort.
const (
	DateAsc     SearchSort = "date_asc"
	DateDesc    SearchSort = "date_desc"
	PopularDesc SearchSort = "popular_desc"
)

// Valid indicates whether the value is a known member of the SearchSort enum.
func (e SearchSort) Valid() bool {
	switch e {
	case DateAsc:
		return true
	case DateDesc:
		return true
	case PopularDesc:
		return true
	default:
		return false
	}
}

// Defines values for SearchTarget.
const (
	ExactMatchForTags   SearchTarget = "exact_match_for_tags"
	Keyword             SearchTarget = "keyword"
	PartialMatchForTags SearchTarget = "partial_match_for_tags"
	TitleAndCaption     SearchTarget = "title_and_caption"
)

// Valid indicates whether the value is a known member of the SearchTarget enum.
func (e SearchTarget) Valid() bool {
	switch e {
	case ExactMatchForTags:
		return true
	case Keyword:
		return true
	case PartialMatchForTags:
		return true
	case TitleAndCaption:
		return true
	default:
		return false
	}
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	Authenticated bool       `json:"authenticated"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	UserId        *int64     `json:"user_id,omitempty"`
	UserName      *string    `json:"user_name,omitempty"`
}

// BookmarkDetail defines model for BookmarkDetail.
type BookmarkDetail struct {
	IsBookmarked bool     `json:"is_bookmarked"`
	Restrict     Restrict `json:"restrict"`
}

// BookmarkRequest defines model for BookmarkRequest.
type BookmarkRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// DownloadIllustType Pixiv artwork type the job was created for.
type DownloadIllustType string

// DownloadJob defines model for DownloadJob.
type DownloadJob struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	IllustId  int64     `json:"illust_id"`

	// IllustType Pixiv artwork type the job was created for.
	IllustType DownloadIllustType `json:"illust_type"`

	// PreviewUrl Thumbnail (square_medium → medium → large). Absent on jobs persisted before this field existed.
	PreviewUrl *string `json:"preview_url,omitempty"`

	// Status Lifecycle state of a download job or task.
	Status    DownloadStatus `json:"status"`
	Tasks     []DownloadTask `json:"tasks"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// DownloadJobList defines model for DownloadJobList.
type DownloadJobList struct {
	// ActiveCount Global count of `queued` + `running` jobs (independent of filter).
	// Drives the sidebar badge.
	ActiveCount int `json:"active_count"`

	// DoneCount Global count of `completed` jobs (independent of filter).
	DoneCount int           `json:"done_count"`
	Jobs      []DownloadJob `json:"jobs"`

	// Page Echo of the requested 1-based page index after clamping.
	Page int `json:"page"`

	// PerPage Echo of the effective page size after clamping.
	PerPage int `json:"per_page"`

	// Total Total jobs matching the filter (status + updated_since).
	Total int `json:"total"`
}

// DownloadStatus Lifecycle state of a download job or task.
type DownloadStatus string

// DownloadTask defines model for DownloadTask.
type DownloadTask struct {
	DownloadedBytes int64   `json:"downloaded_bytes"`
	Error           *string `json:"error,omitempty"`

	// FilePath Target path on disk.
	FilePath   string     `json:"file_path"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Id         string     `json:"id"`
	JobId      string     `json:"job_id"`

	// SizeBytes Content-Length, or -1 if unknown.
	SizeBytes int64      `json:"size_bytes"`
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Lifecycle state of a download job or task.
	Status DownloadStatus `json:"status"`

	// Url Final request URL (after pximg mirror rewrite).
	Url string `json:"url"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code.
	Code string `json:"code"`

	// Detail Optional additional context (e.g., upstream body).
	Detail *string `json:"detail,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// FollowRequest defines model for FollowRequest.
type FollowRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// Illust Pixiv illustration metadata. Shape mirrors pixivgo.IllustrationInfo.
type Illust = pixivgo.IllustrationInfo

// IllustDetailResponse Wrapper for a single illust detail. Mirrors pixivgo.IllustDetailResponse.
type IllustDetailResponse = pixivgo.IllustDetailResponse

// IllustPage defines model for IllustPage.
type IllustPage struct {
	Illusts []Illust `json:"illusts"`

	// NextMaxBookmarkId Set only by `/users/{id}/bookmarks`; pass back as `max_bookmark_id`.
	NextMaxBookmarkId *int64 `json:"next_max_bookmark_id,omitempty"`

	// NextOffset Next offset to pass back, or null if no further page.
	NextOffset *int64 `json:"next_offset,omitempty"`
}

// IllustType defines model for IllustType.
type IllustType string

// IllustrationTag defines model for IllustrationTag.
type IllustrationTag = pixivgo.IllustrationTag

// ImageUrls defines model for ImageUrls.
type ImageUrls = pixivgo.ImageUrls

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// RefreshToken Long-lived Pixiv OAuth refresh token. See README for how to obtain.
	RefreshToken string `json:"refresh_token"`
}

// MetaPage defines model for MetaPage.
type MetaPage = pixivgo.MetaPage

// MetaSinglePage defines model for MetaSinglePage.
type MetaSinglePage = pixivgo.MetaSinglePage

// Novel Pixiv novel metadata. Shape mirrors pixivgo.NovelInfo.
type Novel = pixivgo.NovelInfo

// NovelTag defines model for NovelTag.
type NovelTag = pixivgo.NovelTag

// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
type Profile = pixivgo.Profile

// ProfileImageUrls defines model for ProfileImageUrls.
type ProfileImageUrls = pixivgo.ProfileImageUrls

// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
type ProfilePublicity = pixivgo.ProfilePublicity

// RankingMode defines model for RankingMode.
type RankingMode string

// Restrict defines model for Restrict.
type Restrict string

// SearchSort defines model for SearchSort.
type SearchSort string

// SearchTarget defines model for SearchTarget.
type SearchTarget string

// Series Pixiv returns `{}` instead of `null` for empty series; in that case `id` is 0.
type Series = pixivgo.Series

// SubmitDownloadRequest defines model for SubmitDownloadRequest.
type SubmitDownloadRequest struct {
	// IllustId Pixiv illustration ID.
	IllustId int64 `json:"illust_id"`
}

// UgoiraFrame defines model for UgoiraFrame.
type UgoiraFrame = pixivgo.UgoiraFrame

// UgoiraMetadata defines model for UgoiraMetadata.
type UgoiraMetadata = pixivgo.UgoiraMetadata

// UgoiraMetadataResponse Ugoira (animated illust) metadata. Mirrors pixivgo.UgoiraMetadataResponse.
type UgoiraMetadataResponse = pixivgo.UgoiraMetadataResponse

// UgoiraZipUrls defines model for UgoiraZipUrls.
type UgoiraZipUrls = pixivgo.UgoiraZipUrls

// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
type User = pixivgo.UserInfo

// UserDetailPage defines model for UserDetailPage.
type UserDetailPage struct {
	// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
	Profile Profile `json:"profile"`

	// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
	ProfilePublicity ProfilePublicity `json:"profile_publicity"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`

	// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
	Workspace Workspace `json:"workspace"`
}

// UserIllustsPage defines model for UserIllustsPage.
type UserIllustsPage struct {
	Illusts    []Illust `json:"illusts"`
	NextOffset *int64   `json:"next_offset,omitempty"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`
}

// UserPreview User + a few sample illusts. Shape mirrors pixivgo.UserPreview.
type UserPreview = pixivgo.UserPreview

// UserPreviewPage defines model for UserPreviewPage.
type UserPreviewPage struct {
	NextOffset   *int64        `json:"next_offset,omitempty"`
	UserPreviews []UserPreview `json:"user_previews"`
}

// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
type Workspace = pixivgo.Workspace

// DownloadIdPath defines model for DownloadIdPath.
type DownloadIdPath = string

// DownloadPageQuery defines model for DownloadPageQuery.
type DownloadPageQuery = int

// DownloadPerPageQuery defines model for DownloadPerPageQuery.
type DownloadPerPageQuery = int

// DownloadStatusListQuery defines model for DownloadStatusListQuery.
type DownloadStatusListQuery = string

// DownloadUpdatedSinceQuery defines model for DownloadUpdatedSinceQuery.
type DownloadUpdatedSinceQuery = time.Time

// IllustIdPath defines model for IllustIdPath.
type IllustIdPath = int64

// IllustTypeQuery defines model for IllustTypeQuery.
type IllustTypeQuery = IllustType

// MaxBookmarkIdQuery defines model for MaxBookmarkIdQuery.
type MaxBookmarkIdQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// RestrictQuery defines model for RestrictQuery.
type RestrictQuery = Restrict

// UserIdPath defines model for UserIdPath.
type UserIdPath = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// Upstream defines model for Upstream.
type Upstream = Error

// ListDownloadsParams defines parameters for ListDownloads.
type ListDownloadsParams struct {
	// Status Comma-separated subset of `DownloadStatus` to include. Omit for no
	// filter. Example: `queued,running`.
	Status *DownloadStatusListQuery `form:"status,omitempty" json:"status,omitempty"`

	// Page 1-based page index.
	Page *DownloadPageQuery `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page; clamped to `[1, 100]`.
	PerPage *DownloadPerPageQuery `form:"per_page,omitempty" json:"per_page,omitempty"`

	// UpdatedSince RFC3339 timestamp. Only jobs with `updated_at >= updated_since`
	// are returned. Used by the frontend to load the recent-tracked
	// window without scanning the whole history.
	UpdatedSince *DownloadUpdatedSinceQuery `form:"updated_since,omitempty" json:"updated_since,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// Topics Comma-separated topic filter (e.g. `download,system`).
	// Omit for all topics.
	Topics *string `form:"topics,omitempty" json:"topics,omitempty"`
}

// ListFollowingIllustsParams defines parameters for ListFollowingIllusts.
type ListFollowingIllustsParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRankingParams defines parameters for ListRanking.
type ListRankingParams struct {
	Mode *RankingMode `form:"mode,omitempty" json:"mode,omitempty"`

	// Date Ranking date in `YYYY-MM-DD`. Omit for the latest.
	Date *string `form:"date,omitempty" json:"date,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRecommendedParams defines parameters for ListRecommended.
type ListRecommendedParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchIllustsParams defines parameters for SearchIllusts.
type SearchIllustsParams struct {
	Word         string        `form:"word" json:"word"`
	SearchTarget *SearchTarget `form:"search_target,omitempty" json:"search_target,omitempty"`
	Sort         *SearchSort   `form:"sort,omitempty" json:"sort,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Word string `form:"word" json:"word"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUserBookmarksParams defines parameters for ListUserBookmarks.
type ListUserBookmarksParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// MaxBookmarkId Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response.
	MaxBookmarkId *MaxBookmarkIdQuery `form:"max_bookmark_id,omitempty" json:"max_bookmark_id,omitempty"`
}

// ListUserFollowingParams defines parameters for ListUserFollowing.
type ListUserFollowingParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUserIllustsParams defines parameters for ListUserIllusts.
type ListUserIllustsParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SubmitDownloadJSONRequestBody defines body for SubmitDownload for application/json ContentType.
type SubmitDownloadJSONRequestBody = SubmitDownloadRequest

// AddBookmarkJSONRequestBody defines body for AddBookmark for application/json ContentType.
type AddBookmarkJSONRequestBody = BookmarkRequest

// AddFollowJSONRequestBody defines body for AddFollow for application/json ContentType.
type AddFollowJSONRequestBody = FollowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with a refresh token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current auth status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// List download jobs (paginated)
	// (GET /downloads)
	ListDownloads(w http.ResponseWriter, r *http.Request, params ListDownloadsParams)
	// Submit a download job
	// (POST /downloads)
	SubmitDownload(w http.ResponseWriter, r *http.Request)
	// Remove a download job from history
	// (DELETE /downloads/{id})
	RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Get a download job
	// (GET /downloads/{id})
	GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Cancel a running download job
	// (POST /downloads/{id}/cancel)
	CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Subscribe to the event stream
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List illusts from followed users
	// (GET /illusts/following)
	ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams)
	// List ranked illusts
	// (GET /illusts/ranking)
	ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams)
	// List recommended illusts
	// (GET /illusts/recommended)
	ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams)
	// Get illust detail
	// (GET /illusts/{id})
	GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Remove an illust bookmark
	// (DELETE /illusts/{id}/bookmark)
	DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get current user's bookmark detail for an illust
	// (GET /illusts/{id}/bookmark)
	GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Bookmark an illust
	// (PUT /illusts/{id}/bookmark)
	AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get ugoira metadata
	// (GET /illusts/{id}/ugoira)
	GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Search illusts
	// (GET /search/illusts)
	SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams)
	// Search users
	// (GET /search/users)
	SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams)
	// Get a user's profile detail
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// List a user's bookmarks
	// (GET /users/{id}/bookmarks)
	ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams)
	// Unfollow a user
	// (DELETE /users/{id}/follow)
	DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// Follow a user
	// (PUT /users/{id}/follow)
	AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// List users followed by a user
	// (GET /users/{id}/following)
	ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams)
	// List illusts by a user
	// (GET /users/{id}/illusts)
	ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in with a refresh token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current auth status
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List download jobs (paginated)
// (GET /downloads)
func (_ Unimplemented) ListDownloads(w http.ResponseWriter, r *http.Request, params ListDownloadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a download job
// (POST /downloads)
func (_ Unimplemented) SubmitDownload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a download job from history
// (DELETE /downloads/{id})
func (_ Unimplemented) RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a download job
// (GET /downloads/{id})
func (_ Unimplemented) GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a running download job
// (POST /downloads/{id}/cancel)
func (_ Unimplemented) CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subscribe to the event stream
// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts from followed users
// (GET /illusts/following)
func (_ Unimplemented) ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ranked illusts
// (GET /illusts/ranking)
func (_ Unimplemented) ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recommended illusts
// (GET /illusts/recommended)
func (_ Unimplemented) ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get illust detail
// (GET /illusts/{id})
func (_ Unimplemented) GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an illust bookmark
// (DELETE /illusts/{id}/bookmark)
func (_ Unimplemented) DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user's bookmark detail for an illust
// (GET /illusts/{id}/bookmark)
func (_ Unimplemented) GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bookmark an illust
// (PUT /illusts/{id}/bookmark)
func (_ Unimplemented) AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ugoira metadata
// (GET /illusts/{id}/ugoira)
func (_ Unimplemented) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search illusts
// (GET /search/illusts)
func (_ Unimplemented) SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search users
// (GET /search/users)
func (_ Unimplemented) SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user's profile detail
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a user's bookmarks
// (GET /users/{id}/bookmarks)
func (_ Unimplemented) ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfollow a user
// (DELETE /users/{id}/follow)
func (_ Unimplemented) DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow a user
// (PUT /users/{id}/follow)
func (_ Unimplemented) AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users followed by a user
// (GET /users/{id}/following)
func (_ Unimplemented) ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts by a user
// (GET /users/{id}/illusts)
func (_ Unimplemented) ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDownloads operation middleware
func (siw *ServerInterfaceWrapper) ListDownloads(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDownloadsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_since", r.URL.Query(), &params.UpdatedSince, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDownloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitDownload operation middleware
func (siw *ServerInterfaceWrapper) SubmitDownload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitDownload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveDownload operation middleware
func (siw *ServerInterfaceWrapper) RemoveDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDownload operation middleware
func (siw *ServerInterfaceWrapper) GetDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelDownload operation middleware
func (siw *ServerInterfaceWrapper) CancelDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "topics" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topics", r.URL.Query(), &params.Topics, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topics", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFollowingIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListFollowingIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowingIllustsParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFollowingIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRanking operation middleware
func (siw *ServerInterfaceWrapper) ListRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRankingParams

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mode", r.URL.Query(), &params.Mode, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mode", Err: err})
		return
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecommended operation middleware
func (siw *ServerInterfaceWrapper) ListRecommended(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecommendedParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecommended(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIllust operation middleware
func (siw *ServerInterfaceWrapper) GetIllust(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIllust(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBookmark operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookmarkDetail operation middleware
func (siw *ServerInterfaceWrapper) GetBookmarkDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookmarkDetail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBookmark operation middleware
func (siw *ServerInterfaceWrapper) AddBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUgoiraMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUgoiraMetadata(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchIllusts operation middleware
func (siw *ServerInterfaceWrapper) SearchIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchIllustsParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "search_target" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search_target", r.URL.Query(), &params.SearchTarget, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search_target", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchUsers operation middleware
func (siw *ServerInterfaceWrapper) SearchUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserBookmarks operation middleware
func (siw *ServerInterfaceWrapper) ListUserBookmarks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserBookmarksParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "max_bookmark_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_bookmark_id", r.URL.Query(), &params.MaxBookmarkId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_bookmark_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserBookmarks(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFollow operation middleware
func (siw *ServerInterfaceWrapper) DeleteFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFollow operation middleware
func (siw *ServerInterfaceWrapper) AddFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserFollowing operation middleware
func (siw *ServerInterfaceWrapper) ListUserFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserFollowingParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserFollowing(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListUserIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserIllustsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserIllusts(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads", wrapper.ListDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads", wrapper.SubmitDownload)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/downloads/{id}", wrapper.RemoveDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}", wrapper.GetDownload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads/{id}/cancel", wrapper.CancelDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/following", wrapper.ListFollowingIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/ranking", wrapper.ListRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/recommended", wrapper.ListRecommended)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}", wrapper.GetIllust)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/illusts/{id}/bookmark", wrapper.DeleteBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/bookmark", wrapper.GetBookmarkDetail)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/illusts/{id}/bookmark", wrapper.AddBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/ugoira", wrapper.GetUgoiraMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/illusts", wrapper.SearchIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/users", wrapper.SearchUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/bookmarks", wrapper.ListUserBookmarks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/follow", wrapper.DeleteFollow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/follow", wrapper.AddFollow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/following", wrapper.ListUserFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/illusts", wrapper.ListUserIllusts)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w965LbNnevcob9ZmJPKO360k5jT384sZ1vM3G83bWbSSNXhMgjCVkSoAFwdxXPzvRX",
	"H6DTJ/yepIML76BErbW+fO0/icTl4NzPAXD4IYh5lnOGTMngyYcgJ4JkqFCYf8/5FUs5SU6SU6LW+kmC",
	"MhY0V5Sz4En1Hv7gC6AJMkWXFAUIVIVgmMBiA9Hp6/M3cJS4pjKaBmFAde9cjxkGjGQYPAloEoSBwPcF",
	"FZgET5QoMAxkvMaM6Ikzyn5GttJQPAgDtcl1H6kEZavg5iasQDklK/zXAsWmD+2DyYJITCAnKwTKEryu",
	"QHlvelSw6BZBc/YEl6RIlZk7o4xmRdaEgzKFKxRtQFBsgeVEYSYhR2GgeQpxSrIcE1Acot8fhPDg+Phd",
	"NAgeivkwiA+PwyAj1w7G4+PREJ8rogr5M5VqAOgfeJaRiUTNJAoTkMVCogK+hKg9RqTXQVmcFglO4XVG",
	"FSy5AMZnbElThWIKL65Jlqf4BKL3BRaYhKJgjLJVNJ2xIAzQvrZrb7wewIg007bwMcwib/NEg39OWTxE",
	"nrOXPzx69Og7UDRDqUiWT+E1SzeazyVcUbWGqLCjzImCWXF8/Aj/BcpHUo8czRgRWInCFN5KKxBqjbAU",
	"nClkht5GgPRDgTEyNVGCxBeYzNgVZQm/MtPxQoGMiUGBaXu15inCmkrFxcaizIeXFkQt9Cy5yIgKngS6",
	"wUSvM/CJ1UmaFlINyf8pvaaXQE0bQfRDOHl+O/mu4KFM/dPjYCfTWsDebPJBCTMNQHcFy3RPYcHVGppU",
	"gas1MuAZVZqf712tUSDIIs+5UJjcHxJAA08T+r8IXAZPgn84qrXpkX0rj2pIDeCvyPX3nF9kRFycJEOC",
	"VgjJhZEZTWyG1woWrpN0GiMnUkKkX80zcj0vX89pEmn2ykzPXOAl5YUEgTLnTOLQijpDBB9DmtfLpcQh",
	"HWJfmqVx83OSkxVlRp+kVCpAluScMiWHQLXd/LrvONwC7bEX2jPU7B4PwftvVNIFTanagIx5jnAvLxYp",
	"jYELyAW9JAoH2US4oUezSgmLAeytRLFd8AqJ4hMJ3I0eyrKQ8Qy+J8kZvi9QKv0vNtrM/CR5ntLY6IKj",
	"P6QG9sPIxb8QgrupOpLMLklKtd0ufZNpcBMGv/Af6mnbPZ7FRhfJIo4RE0yeAuOw4MnGdVQvecGSu4f8",
	"DCUvRIzAuGb5giXAGRjiGUjeMlKotXabYi0Adw/QLxwsLi0DSZSScjaFH0ialp6aBuko5SvKIlhSIZUF",
	"NZdKIMnuHkbH226+WlUTBgXD6xxjrStQd58aQXEj6gmfFWptXRDjzAqeo1DUsmwP1Y7JF5ynSJheJF7n",
	"VKCcEzVoIlmRpmShPRMrUB2TGQZaKLUG9YnYQOdKzFxvK8Afds110xTv3zvre1c154s/UKuUMCjtznNU",
	"hKZ9DFFZ2YAhDFUqbR9N1oSyPUdjwG0AN1RNG+JbgdObpgpzaks9oHGJUFdcXFivQhtYHfhcEQmxQGPC",
	"lpopwwCZVqS/B9Y10sqVsBUJwqBYcSpIY7E145RQ/MQX/YW68bdxZm9Amnj84NDBNMSifZZ07ZVDyzY0",
	"exB5EwbGCcGreSHSPl7frItswQhN4Z58XxCB8wwTWmTwt//6b2j8TIlY4f0pPFtIZEqrUeOL5ygklRrz",
	"C1xyoYlCJSwppgngtXkz9eFGVkpizHqcStG8Q+SFlRUdwI3t/4bIi6DmPCIE2Zj/VKXoJVIdXezhrLfk",
	"TAtXTeo2GcM6YGowVmvWcqnvtsjLT3yho0WPqo0VvcR5zAufdf4x5QuSgnlrgkcb4kXwLURlFGipe09H",
	"6TmyBG1L68ffn87Yc0EvURoRlDTBBRGwIMkKbSjUZ+KEs/HwaEqmqDRIW8HwzqR77M0gWuY9/GGC/B68",
	"L+I112DYmNFoRkygn90AslQobGqBstV0h48X1nmFrVPicomGvnYqSf/EvWdSXBGfMtCPLc4zouJ1Ge1a",
	"hMM9y7XwbTvS9hKiIw6GKuW8YZngaSRSWizb4pdtElD7Gu2F/EyXGG/iFEGDjBp1BJJmtkyHdkReNI2F",
	"FQNtE6tcR8WJQRgsCU3Nj5iwGNO0ZeT7ZsTonJ5kljBgMl9slH02wgYYb2uESxIGS5riPPcGLW+0Cleg",
	"X2r9nVC7fM8QjMr1duW3E44B4/cHX8wHXmlGrpHSzXwZj3diU5Chpt7kAdAlFOyC8Sum1zECjVIRoT5y",
	"Ybe1XF7r+5IykpZKBN6e/Qz3rCjn1zRbQUY13UHglaCqJWfbrI7DsZ2yyRENs9NAdthnSp/IvShZsOMY",
	"8cSjr14RrTxwIpAkGps2XADdeNrKLhadCMyD8KTyljuZDPODpECShLqfJjK6VnAPp6tpWAcxOva872X2",
	"DKX0qty/Fhlh3QW41rsJYdBSj+5D6Euepvzqjl3rvyJJh0OympdrivCLnYtz3XyLsp7nqExlhookRJEp",
	"nK9Jjo7ZJeS66YpPTxqNT9iSa6R3eI+44T3axPpVcy3a3vdrpKu1GuuC7+mrE1q56+M76bBsLtUmHd0v",
	"IyvUXv1ObXSiW77VDXW33VEmlfOsGIzSNeGM2R7vZ71CRU61IHicLDOcpGxl1NQKx4x1bpqXI+petXM5",
	"AnNN2dqjOeVsTpQSdFGozuJ7/NVdpSSMqs08xUtMR04rUZT+fJq+XgZPft+OmHPb/uZd14qZuGk1nlpN",
	"yXtDVvtFTorzdE/cGK+wYsqxPpHtFfMsKzdPR3fS4fDYDk6OvXmmXYh8K+0gl1TSRQtfDXG6oon11kZA",
	"cz3fi3V93oGlXFjuoTSUSFgp1LCZOjcLdRxUkretX1sSWC6oUrEd3m8tomJyjxpoKZoW5focE/byWiXK",
	"G8qsp559qndQ2nvWLgyuJys+cQ+HrFaz2YRmOReGdOVOsu1lMKiZIFhRtS4W05hnR+o6R5EelU3qTTeb",
	"Pjxz2wF9W/urIHmOdvuKgEWpM71gnakpvPIa2/bIfYNLK+u+W330uc8+3guPnaUeHpenzuD41rmvwvSp",
	"Nt/+YJ9i56iAs3RjzmscaYGTRx9ocnNUcXjkNhwXJL4AIiHq7jl6I6Dd+W4Dn9vR64H1i3al7UtQvAbA",
	"xF96bB2BMQ7LQqi1O0pxKzi8nLLNwSxzxAN5Xl9c3jVqPaKXWf++uRKEydTkO263M2B69ce5hUbRgB9U",
	"CCrHsIcOk/D14sNmhf0xfDOF7D8F0gokWs2rkUM3+VgEVYs4JGp+5ivKtkRnS4FyPVf8Apkn/8TZapLS",
	"Syx3+l4/K9QaXC8wvaZwjghnL549f/XC6Oo1v9JixheKULY7xGyD4JOVyuvuK7jbhA5dKa3HGEmoCp5D",
	"0qkTDvSWygVdUUbSeQWvny/HLqAx1yGX8Qt3gYEvbmb65c6A2Qxxi0jZetBzEsco5TzmTAk+NkbZFWaP",
	"j5w/UzCr324MBufaAg82KtlosEHt1Q5NZai4Z27grkPbzxZjGmYdCi61U5K606bjorQt4eiXG1seLIQ8",
	"YFjoDQFbEVtTGLrxYysodBFjKzZskrYKLasYsBvE9cO8VhRYx3gderWDvo6E96W1K5ojzVmlbw9vCLwO",
	"Kklshn5e5C5bXzKQR9d8amc2HAJvH2Qe2r09FXxJU9x6fi+3bYaMqhuib1JJkghtL0dbOB05rQQvWLLV",
	"FQmDBRVW8fnfzBOy2fJ2g0SMNd5aKMVmXu7h9EZcIUtaHNYw7HKeC8zabn7bIhaSstU8LqTi2dyh2S7d",
	"3+UPe/Bmy57hKIN5xXmJ2p2beQJXQ26RVSlLs0ljOHk/M9DILBndNbfHVm8zRm2j9+y5Xx8bOu/Vw6nV",
	"/bFj9e0tFmY6ju5yRZVCoT3b0oPqk9m1GcsxV7goNyn205tlx0qqSkFvinVLiCv2DJvKpiO2Vmwam74e",
	"vvXTq8srbT7oIHwXW/tZ1kvuAU3YJ1ebOE3RbqmfXbpmpAEqbcUd2J8tWZaxmRLXbr+13E1ixA1+aghP",
	"1WbIujoqQF42hGVKVnKHoa2G7VvcfazfPqZsyO4Yfhs6hjtgNzpkq0S9kuRBWbdibOfcj8w1JQ5J5jPC",
	"LihbvXK+QZlptZBfIV4EYZBxZhRYQjbzjBjh0T+X6P7oZs1gwfwXnF9QrHpZZaN/iwf/3Bir8deO5x7Y",
	"MVo/V96E71kjJKouqASVvioXVD1wt0m8Y50jEfH63CG0Hi0x4Q7K5oDNZ+Y3MT9znhcpEfbN8Bz2kFYH",
	"ZiIUNZpZxev5kou5C62qNQw2uCax6j82wd6csGReh3sXuLniIhkArTTUPkG3NwQkRB9uIqBMKiSJOcep",
	"DWRkUpuY5WoD1gA8BcpArYmCmEiEiCYRUAnHnu2m5CPD/+FAd6SEnZcm63BydV4sMqrK82GDCebWKfGR",
	"t/72vSjW33PR8/kyyW/NsfmXwkWMnTONmFqdPIJSZTi2nVDOENuBR5KqCeIh6WXHfeVyr/3VL/WM4/Ne",
	"TTA9qa8/aT4qCWqH+Xeae1Pz1ShhCd5eSKwWe3d4HN69tu3gHmE0M1c6LGfeb6S/u5vX/qH7+sRe/phn",
	"DVruxnGFjC6Su6PdCsV3srXdZo5P5HO2Jz3oclyWazCFI4ssI2Iz5Fmai5zebZFtgaFLJn7kroY02yq5",
	"mota0XuTJW73ZZHyWLtdW1J7VLrozu4zDEShY3KBrThplNrpBRZeE1smBKs4zjNRex1jecxR8uDsZc+Z",
	"+DcQ8zqJOAI1TbzmzRBpRN/akd9zc+CKiwuZk3gnkL9WDXvazKbi8yoK7i+iOY/XSdDUscmET3Kspj62",
	"csuLnuPQ60fUtjMqut+pvXTnsW9aY30LBJZ4BdKcunYmTm5TYG68oTNZh0Dq9o3SOvM2fn/PN8uhEF9B",
	"1AB8DzVS0ufQmsSN6xeAw7Dt3F3o3MPpbCy4RxIPmusZfOz9a1Pb+IxypSaAarM7wNXVMJ7jCmtCxd5W",
	"OUF748r7QvHcf5iJM6q4GHhXyIEjUIW0ufy+TR14LDQR/dOYwjID75RmBzV40Nr7okJ/e59pv3R1Hgc1",
	"ctxkNagVYCWS6hXW6C7R5CgTOrLWRPSDOlKIay48nAhrJGiWHWDs72kBl4/MEUhkCTw7PZnCGZJkYs9u",
	"Cn4lKVtp5V6oNXxblYw5sn7OdMZOiVqDEVlTBkfmKVVAYsGlBG1tJRQsQQGRBlYeRbDYQMIzQtnTGXPS",
	"DIQlINdEYLMkB0hFNhAjU4KkVGICaxTldVybHmkt4tnpSRAGlyikXeDx9MH0WHMPz5GRnAZPgkfT4+kj",
	"hzgjlo3SFEa3cd9NnxfX8ZqwlbscPHj6rTydvOZCuZNy1gWeMfter9LdLpdAFUgUlygmkib41Fa+el8g",
	"U9C6PzZjVfkaEFhItIkmqbjGVlluwyBF6xt7SjsxB/b0oqwIoFTf82RzsEobrZOEN21Bc0dnWrVdHh4f",
	"H2zuRkEOT6mPZ03cTeHNGh0RHI2orFFXYd+UI3lsYfRNXa3lqFGkxnR5sLtLtyLLTRj84/HDEf3K8iim",
	"IImNBy1ZgTJbMYy0GbA8oOIqdwTvdM+Kw3mhhln8hxSJsPxd1z8wg1rhFJjx8nY8Z5OEygt3D9meNDhJ",
	"MMu5Ju7Ux4h67h5LPN6Ng7ogTx8JvFAGnLgQQkuNE4UtSKjvBrp8dBvOH1E1eOuzcfAPbj1G41qQp53l",
	"/4iqWnajmX/pVZnExsK7Z/WNJLSrZk3htdB6m0pgeIVSuco98KsrHmdv0MsZw0sUG1uvUVa1dUJYFEor",
	"/RVGcARReS8+ApJekY0Ejb7NdMbKdBHERAjqWMzssbryCXlaSFjZggpR8059BEczFtXX6iOQHOKUalxD",
	"wtk3ChhqJQxlfUE7oqwKgnnVJpVVKtue9arLVw6cJKybHA0VPrwJR3etSzzu06lZGnKPfv3ChTfv7pDz",
	"u2U+POz/E19IW7bN3r34lJq5rWM0DM0CCxLuVSJyvyFrtYC9026xV7+eoeRpqUDdxaWybpcWFZomEjhD",
	"U8GhKuIJ97jQT2dMP7HZWfiT5vdDQGZqO9gBtc8ZOj1tN67005/4whjAGSuXrAU0enj8EJ6ZDB4m0VOr",
	"Qo3QgPXpJOSCr4Q2mZeUzJhuEJVrjEDxnMYa9ujHF2/gCC81UiOfJLW3he7IE/HvPY1ySR7eBVsPsDQQ",
	"h/FP7Wo8HmdmXfm6j/RNLDE6dUkGJKVlmszVMLfxhsoThT83zyUQUCgyU2JCG5x7VTUTOAJbzQSOoKpm",
	"cr8qWzljxuuzDmFVY9iIONWjurKnkPLVE1vwqeHxaAGKuUjshba//ef/AEkFkmQzqctMuFjHFSExoRDj",
	"ChQv4jUmxs65LeXHx99FQJdVrS/jkdI0BVejxUzQkMqskGrGujWP7WU6u9KyqB684WARaKEJQYcLxPyZ",
	"sYwwskLhk9Qzs9aGpN7O6LnSkh4Lsp+r9wm5/fHxd3dffvCnISpb8ulQ0JUaM0xnyh21BcsSqFvwxzC3",
	"49xBezTk6t4htY8/lWJ9Y0Vo+glZpueH31LZOdHdEpGZ9xKsd804m1Saz/gI5sSJXT5s0y1OVen2DeVp",
	"Yrd+qGYn/X9FcLeKYCtJ2hxmCaIDfac2RjKbdcsGI77GZc5I4bWy7SfWqEcQc8bQlAuYwgszkjFoapPb",
	"fNQlpjxHCdEHmoSgZGi9wtC0CCEhitxEgK4G9kKvVKFgJJ0xWSzkRpp04b0K6NBEsSHYN/etlS7NH9m4",
	"UHPGzCzGLTUcHtn/EZgiyXXm8KkWAVeBO7QC5Ppq7CeoFy6MUdZm2S0WFrgml5QXovKDTSlARVhCRALn",
	"5y9AYkY0l8kpnCytZ+CglMgS7UdEPxOpJgZnk5PnEayR6CBau+amtp4m4aJYLvVqrD1Yc+366xBbgKVa",
	"aCc2QTkIzFMdLqs1Zs5KGH++yPRQeiXlgjYlUHDyHNZEwgKRAV6aC0HNMWfMuAsVzK6cQmSxPxUoNyyO",
	"LDA6pK59kZkpTSZBcRA4WaKK14ZyXFBFTP0+mxMqCXT24vxNo/q2x/P4EZVlsL6u2f6hAEvOsoofTlfT",
	"OkgJ7Uqi+9MZq74UQNLUdpLDte3t+1Zt7bqKVGd0z2Xm3ZawJ2ttpeJNy5xrMjgptEeffBepe7rmdW6o",
	"b2hoppoeKC4+LxZ6ngVqNjDVGxuTNFSSU0FWH61N0a5tqTdb1usu026twmEejGl809gEyRbcTU8brzG+",
	"MFKk261LiMsVO8awK3abum6jRBNpaPE6CnlZtjqp9oL3M73tmvMjMkDNkvp36sM1qpJ4kF4tHJboSo1O",
	"P1tq3YSDlgDWuS5P80B1v8SRujor0aK1sAfMt1LaHULvE9j7DQV7H6ZG9Lgrzc2D7pq2zdPdZnu8l56y",
	"HbTlRu2WRL/99ttvk1evJs+fR42vrWhpT4lCqYa+T+DuydYA50Rp0x88Cf7j9+PJd+8+PL6Z2B8P6x9/",
	"8VWG+Fo4uMTd52ddzX7V6dIR3Ip21zqx52OGObbRbl+11P2myldE1nLV9jj6F0DdmgyjSVym1YaM7klZ",
	"ZOg2VP0UCQBvzSzfBz2aVwdcRbCvJm36I6p2MbNRdK0qabXzpm0a27xp+dGDgxP6iw3nP4YcZbKNlURZ",
	"1Ojrk2U4w9b5NsaXK2QdQD3iVbb4KkWr3CnXPtw3sqKmW4sNDktaD5A4LzwkfpYkhxSsw++Ndb91ctP/",
	"6NLfqQhX/LqdsD2V6r6lMpQ2O2vsrppQfKKoycNkhNElSlUlev6kual9npP4gqwoW80Yknhte9Uf7itP",
	"K5iEijkmZ3aEv5FQ3hWaseatuKEcSu+S05eqagauCnlUjrs0VV2R+qpUTtEGfpD5pLkge9Q48O7lu1dE",
	"xWuUmmPcnVb7sYfVU5CIENlh5spctLXXU6uPXegQ0rBlJLlwL7lIULivanT27M1Ig0kIX8hnrth+xHdW",
	"/aO2ljT6a3etC8fDY3Ox75DmnvRXFJRaqEGgLFIlP8NRmo88SGDB74c5li3a0lPVatkqO/bYbkJlnpIN",
	"aE7QMuQudA0JwluX9vkkYvClcFb3zodPOZs7ii0e+wrZq5vUazFXXbJ4WwD91t0x28vcNj7DeeeEbFwD",
	"HKLj1+jTk9KbL0uy9AJnS9wuLY9aZRO9CsN+KbdxGnax8dSmhlMi5Yzt/bVcILL6AO+MxWauoWOomjrf",
	"NyoF3p7LwsPvH3g+OvwZ7d33rU8ZT4e+YkwlSFT2E82E8arEt/2wn/x6ZMBkBEk3pJW7+d/uaOxOGdl9",
	"mQOrtr/LWPMtszh15PCQYDh/cCgsHz530P6U0/+dzMHLHbT0itOuPT9Nr2qj80tT5F+SX1nvBn/0fsun",
	"V8eGLeot48VmNBf1438/D932cMB+HPQl79l1CzIM+bTlLv5XyEYl6Fv5x9Y5vyzpb+5DB0ckp0eXDwwF",
	"XI/q0rA7m6Jp6Z6YK2KN/yUTNh7Z6RoPXITUeFIfPGw8dEd/bt7d/G8AAAD//41xdpYNiAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
