// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	pixivgo "github.com/txperl/pixivgo"
)

// Defines values for ClientMode.
const (
	ForIos ClientMode = "for_ios"
	None   ClientMode = "none"
)

// Valid indicates whether the value is a known member of the ClientMode enum.
func (e ClientMode) Valid() bool {
	switch e {
	case ForIos:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for DownloadIllustType.
const (
	DownloadIllustTypeIllust DownloadIllustType = "illust"
	DownloadIllustTypeManga  DownloadIllustType = "manga"
	DownloadIllustTypeUgoira DownloadIllustType = "ugoira"
)

// Valid indicates whether the value is a known member of the DownloadIllustType enum.
func (e DownloadIllustType) Valid() bool {
	switch e {
	case DownloadIllustTypeIllust:
		return true
	case DownloadIllustTypeManga:
		return true
	case DownloadIllustTypeUgoira:
		return true
	default:
		return false
	}
}

// Defines values for DownloadStatus.
const (
	Cancelled DownloadStatus = "cancelled"
	Completed DownloadStatus = "completed"
	Failed    DownloadStatus = "failed"
	Queued    DownloadStatus = "queued"
	Running   DownloadStatus = "running"
)

// Valid indicates whether the value is a known member of the DownloadStatus enum.
func (e DownloadStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for IllustType.
const (
	IllustTypeIllust IllustType = "illust"
	IllustTypeManga  IllustType = "manga"
)

// Valid indicates whether the value is a known member of the IllustType enum.
func (e IllustType) Valid() bool {
	switch e {
	case IllustTypeIllust:
		return true
	case IllustTypeManga:
		return true
	default:
		return false
	}
}

// Defines values for RankingMode.
const (
	Day          RankingMode = "day"
	DayFemale    RankingMode = "day_female"
	DayFemaleR18 RankingMode = "day_female_r18"
	DayMale      RankingMode = "day_male"
	DayMaleR18   RankingMode = "day_male_r18"
	DayManga     RankingMode = "day_manga"
	DayR18       RankingMode = "day_r18"
	Month        RankingMode = "month"
	Week         RankingMode = "week"
	WeekOriginal RankingMode = "week_original"
	WeekR18      RankingMode = "week_r18"
	WeekR18g     RankingMode = "week_r18g"
	WeekRookie   RankingMode = "week_rookie"
)

// Valid indicates whether the value is a known member of the RankingMode enum.
func (e RankingMode) Valid() bool {
	switch e {
	case Day:
		return true
	case DayFemale:
		return true
	case DayFemaleR18:
		return true
	case DayMale:
		return true
	case DayMaleR18:
		return true
	case DayManga:
		return true
	case DayR18:
		return true
	case Month:
		return true
	case Week:
		return true
	case WeekOriginal:
		return true
	case WeekR18:
		return true
	case WeekR18g:
		return true
	case WeekRookie:
		return true
	default:
		return false
	}
}

// Defines values for Restrict.
const (
	Private Restrict = "private"
	Public  Restrict = "public"
)

// Valid indicates whether the value is a known member of the Restrict enum.
func (e Restrict) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for SearchDuration.
const (
	WithinLastDay   SearchDuration = "within_last_day"
	WithinLastMonth SearchDuration = "within_last_month"
	WithinLastWeek  SearchDuration = "within_last_week"
)

// Valid indicates whether the value is a known member of the SearchDuration enum.
func (e SearchDuration) Valid() bool {
	switch e {
	case WithinLastDay:
		return true
	case WithinLastMonth:
		return true
	case WithinLastWeek:
		return true
	default:
		return false
	}
}

// Defines values for SearchSort.
const (
	DateAsc     SearchSort = "date_asc"
	DateDesc    SearchSort = "date_desc"
	PopularDesc SearchSort = "popular_desc"
)

// Valid indicates whether the value is a known member of the SearchSort enum.
func (e SearchSort) Valid() bool {
	switch e {
	case DateAsc:
		return true
	case DateDesc:
		return true
	case PopularDesc:
		return true
	default:
		return false
	}
}

// Defines values for SearchTarget.
const (
	ExactMatchForTags   SearchTarget = "exact_match_for_tags"
	Keyword             SearchTarget = "keyword"
	PartialMatchForTags SearchTarget = "partial_match_for_tags"
	TitleAndCaption     SearchTarget = "title_and_caption"
)

// Valid indicates whether the value is a known member of the SearchTarget enum.
func (e SearchTarget) Valid() bool {
	switch e {
	case ExactMatchForTags:
		return true
	case Keyword:
		return true
	case PartialMatchForTags:
		return true
	case TitleAndCaption:
		return true
	default:
		return false
	}
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	Authenticated bool       `json:"authenticated"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	UserId        *int64     `json:"user_id,omitempty"`
	UserName      *string    `json:"user_name,omitempty"`
}

// BookmarkDetail defines model for BookmarkDetail.
type BookmarkDetail struct {
	IsBookmarked bool     `json:"is_bookmarked"`
	Restrict     Restrict `json:"restrict"`
}

// BookmarkRequest defines model for BookmarkRequest.
type BookmarkRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// ClearDownloadsResponse defines model for ClearDownloadsResponse.
type ClearDownloadsResponse struct {
	// Removed Number of jobs deleted from history.
	Removed int `json:"removed"`
}

// ClientMode Pixiv `filter` knob — controls iOS-app-style content gating.
// `for_ios` applies Pixiv's iOS-client policy filter; `none` disables
// it. Named `client_mode` here to avoid collision with the generic
// notion of "filtering".
type ClientMode string

// DownloadIllustType Pixiv artwork type the job was created for.
type DownloadIllustType string

// DownloadJob defines model for DownloadJob.
type DownloadJob struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	IllustId  int64     `json:"illust_id"`

	// IllustType Pixiv artwork type the job was created for.
	IllustType DownloadIllustType `json:"illust_type"`

	// PreviewUrl Thumbnail (square_medium → medium → large). Absent on jobs persisted before this field existed.
	PreviewUrl *string `json:"preview_url,omitempty"`

	// Status Lifecycle state of a download job or task.
	Status    DownloadStatus `json:"status"`
	Tasks     []DownloadTask `json:"tasks"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// DownloadJobList defines model for DownloadJobList.
type DownloadJobList struct {
	// ActiveCount Global count of `queued` + `running` jobs (independent of filter).
	// Drives the sidebar badge.
	ActiveCount int `json:"active_count"`

	// DoneCount Global count of `completed` jobs (independent of filter).
	DoneCount int           `json:"done_count"`
	Jobs      []DownloadJob `json:"jobs"`

	// Page Echo of the requested 1-based page index after clamping.
	Page int `json:"page"`

	// PerPage Echo of the effective page size after clamping.
	PerPage int `json:"per_page"`

	// Total Total jobs matching the filter (status + updated_since).
	Total int `json:"total"`
}

// DownloadStatus Lifecycle state of a download job or task.
type DownloadStatus string

// DownloadTask defines model for DownloadTask.
type DownloadTask struct {
	DownloadedBytes int64   `json:"downloaded_bytes"`
	Error           *string `json:"error,omitempty"`

	// FilePath Target path on disk.
	FilePath   string     `json:"file_path"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Id         string     `json:"id"`
	JobId      string     `json:"job_id"`

	// SizeBytes Content-Length, or -1 if unknown.
	SizeBytes int64      `json:"size_bytes"`
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Lifecycle state of a download job or task.
	Status DownloadStatus `json:"status"`

	// Url Final request URL (after pximg mirror rewrite).
	Url string `json:"url"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code.
	Code string `json:"code"`

	// Detail Optional additional context (e.g., upstream body).
	Detail *string `json:"detail,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// FollowRequest defines model for FollowRequest.
type FollowRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// Illust Pixiv illustration metadata. Shape mirrors pixivgo.IllustrationInfo.
type Illust = pixivgo.IllustrationInfo

// IllustDetailResponse Wrapper for a single illust detail. Mirrors pixivgo.IllustDetailResponse.
type IllustDetailResponse = pixivgo.IllustDetailResponse

// IllustPage defines model for IllustPage.
type IllustPage struct {
	Illusts []Illust `json:"illusts"`

	// NextMaxBookmarkId Set only by `/users/{id}/bookmarks`; pass back as `max_bookmark_id`.
	NextMaxBookmarkId *int64 `json:"next_max_bookmark_id,omitempty"`

	// NextOffset Next offset to pass back, or null if no further page.
	NextOffset *int64 `json:"next_offset,omitempty"`
}

// IllustType defines model for IllustType.
type IllustType string

// IllustrationTag defines model for IllustrationTag.
type IllustrationTag = pixivgo.IllustrationTag

// ImageUrls defines model for ImageUrls.
type ImageUrls = pixivgo.ImageUrls

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// RefreshToken Long-lived Pixiv OAuth refresh token. See README for how to obtain.
	RefreshToken string `json:"refresh_token"`
}

// MetaPage defines model for MetaPage.
type MetaPage = pixivgo.MetaPage

// MetaSinglePage defines model for MetaSinglePage.
type MetaSinglePage = pixivgo.MetaSinglePage

// Novel Pixiv novel metadata. Shape mirrors pixivgo.NovelInfo.
type Novel = pixivgo.NovelInfo

// NovelTag defines model for NovelTag.
type NovelTag = pixivgo.NovelTag

// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
type Profile = pixivgo.Profile

// ProfileImageUrls defines model for ProfileImageUrls.
type ProfileImageUrls = pixivgo.ProfileImageUrls

// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
type ProfilePublicity = pixivgo.ProfilePublicity

// RankingMode defines model for RankingMode.
type RankingMode string

// Restrict defines model for Restrict.
type Restrict string

// SearchDuration defines model for SearchDuration.
type SearchDuration string

// SearchSort defines model for SearchSort.
type SearchSort string

// SearchTarget defines model for SearchTarget.
type SearchTarget string

// Series Pixiv returns `{}` instead of `null` for empty series; in that case `id` is 0.
type Series = pixivgo.Series

// SubmitDownloadRequest defines model for SubmitDownloadRequest.
type SubmitDownloadRequest struct {
	// IllustId Pixiv illustration ID.
	IllustId int64 `json:"illust_id"`
}

// UgoiraFrame defines model for UgoiraFrame.
type UgoiraFrame = pixivgo.UgoiraFrame

// UgoiraMetadata defines model for UgoiraMetadata.
type UgoiraMetadata = pixivgo.UgoiraMetadata

// UgoiraMetadataResponse Ugoira (animated illust) metadata. Mirrors pixivgo.UgoiraMetadataResponse.
type UgoiraMetadataResponse = pixivgo.UgoiraMetadataResponse

// UgoiraZipUrls defines model for UgoiraZipUrls.
type UgoiraZipUrls = pixivgo.UgoiraZipUrls

// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
type User = pixivgo.UserInfo

// UserDetailPage defines model for UserDetailPage.
type UserDetailPage struct {
	// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
	Profile Profile `json:"profile"`

	// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
	ProfilePublicity ProfilePublicity `json:"profile_publicity"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`

	// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
	Workspace Workspace `json:"workspace"`
}

// UserIllustsPage defines model for UserIllustsPage.
type UserIllustsPage struct {
	Illusts    []Illust `json:"illusts"`
	NextOffset *int64   `json:"next_offset,omitempty"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`
}

// UserPreview User + a few sample illusts. Shape mirrors pixivgo.UserPreview.
type UserPreview = pixivgo.UserPreview

// UserPreviewPage defines model for UserPreviewPage.
type UserPreviewPage struct {
	NextOffset   *int64        `json:"next_offset,omitempty"`
	UserPreviews []UserPreview `json:"user_previews"`
}

// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
type Workspace = pixivgo.Workspace

// BookmarkTagQuery defines model for BookmarkTagQuery.
type BookmarkTagQuery = string

// ClientModeQuery Pixiv `filter` knob — controls iOS-app-style content gating.
// `for_ios` applies Pixiv's iOS-client policy filter; `none` disables
// it. Named `client_mode` here to avoid collision with the generic
// notion of "filtering".
type ClientModeQuery = ClientMode

// DownloadIdPath defines model for DownloadIdPath.
type DownloadIdPath = string

// DownloadPageQuery defines model for DownloadPageQuery.
type DownloadPageQuery = int

// DownloadPerPageQuery defines model for DownloadPerPageQuery.
type DownloadPerPageQuery = int

// DownloadStatusListQuery defines model for DownloadStatusListQuery.
type DownloadStatusListQuery = string

// DownloadUpdatedSinceQuery defines model for DownloadUpdatedSinceQuery.
type DownloadUpdatedSinceQuery = time.Time

// DurationQuery defines model for DurationQuery.
type DurationQuery = SearchDuration

// ExcludeAiQuery defines model for ExcludeAiQuery.
type ExcludeAiQuery = bool

// IllustIdPath defines model for IllustIdPath.
type IllustIdPath = int64

// IllustTypeQuery defines model for IllustTypeQuery.
type IllustTypeQuery = IllustType

// IncludeRankingIllustsQuery defines model for IncludeRankingIllustsQuery.
type IncludeRankingIllustsQuery = bool

// MaxBookmarkIdQuery defines model for MaxBookmarkIdQuery.
type MaxBookmarkIdQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// RestrictQuery defines model for RestrictQuery.
type RestrictQuery = Restrict

// UserIdPath defines model for UserIdPath.
type UserIdPath = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// Upstream defines model for Upstream.
type Upstream = Error

// ClearDownloadsParams defines parameters for ClearDownloads.
type ClearDownloadsParams struct {
	// Status Comma-separated subset of `DownloadStatus` to include. Omit for no
	// filter. Example: `queued,running`.
	Status *DownloadStatusListQuery `form:"status,omitempty" json:"status,omitempty"`
}

// ListDownloadsParams defines parameters for ListDownloads.
type ListDownloadsParams struct {
	// Status Comma-separated subset of `DownloadStatus` to include. Omit for no
	// filter. Example: `queued,running`.
	Status *DownloadStatusListQuery `form:"status,omitempty" json:"status,omitempty"`

	// Page 1-based page index.
	Page *DownloadPageQuery `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page; clamped to `[1, 100]`.
	PerPage *DownloadPerPageQuery `form:"per_page,omitempty" json:"per_page,omitempty"`

	// UpdatedSince RFC3339 timestamp. Only jobs with `updated_at >= updated_since`
	// are returned. Used by the frontend to load the recent-tracked
	// window without scanning the whole history.
	UpdatedSince *DownloadUpdatedSinceQuery `form:"updated_since,omitempty" json:"updated_since,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// Topics Comma-separated topic filter (e.g. `download,system`).
	// Omit for all topics.
	Topics *string `form:"topics,omitempty" json:"topics,omitempty"`
}

// ListFollowingIllustsParams defines parameters for ListFollowingIllusts.
type ListFollowingIllustsParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRankingParams defines parameters for ListRanking.
type ListRankingParams struct {
	Mode *RankingMode `form:"mode,omitempty" json:"mode,omitempty"`

	// Date Ranking date in `YYYY-MM-DD`. Omit for the latest.
	Date *string `form:"date,omitempty" json:"date,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// ListRecommendedParams defines parameters for ListRecommended.
type ListRecommendedParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`

	// IncludeRankingIllusts When false, omit the daily-ranking section Pixiv injects into the
	// recommended feed. Omit to keep Pixiv's default behaviour.
	IncludeRankingIllusts *IncludeRankingIllustsQuery `form:"include_ranking_illusts,omitempty" json:"include_ranking_illusts,omitempty"`
}

// SearchIllustsParams defines parameters for SearchIllusts.
type SearchIllustsParams struct {
	Word         string        `form:"word" json:"word"`
	SearchTarget *SearchTarget `form:"search_target,omitempty" json:"search_target,omitempty"`
	Sort         *SearchSort   `form:"sort,omitempty" json:"sort,omitempty"`

	// StartDate Lower bound `YYYY-MM-DD` for creation date.
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Upper bound `YYYY-MM-DD` for creation date.
	EndDate *string `form:"end_date,omitempty" json:"end_date,omitempty"`

	// Duration Time-window filter for search results.
	Duration *DurationQuery `form:"duration,omitempty" json:"duration,omitempty"`

	// ExcludeAi When true, exclude AI-generated works from search results
	// (Pixiv `search_ai_type=1`). Omit or set false to include them.
	ExcludeAi *ExcludeAiQuery `form:"exclude_ai,omitempty" json:"exclude_ai,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Word string      `form:"word" json:"word"`
	Sort *SearchSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Duration Time-window filter for search results.
	Duration *DurationQuery `form:"duration,omitempty" json:"duration,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// ListUserBookmarksParams defines parameters for ListUserBookmarks.
type ListUserBookmarksParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// MaxBookmarkId Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response.
	MaxBookmarkId *MaxBookmarkIdQuery `form:"max_bookmark_id,omitempty" json:"max_bookmark_id,omitempty"`

	// Tag Restrict bookmarks to those tagged with this exact tag name.
	Tag *BookmarkTagQuery `form:"tag,omitempty" json:"tag,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// ListUserFollowingParams defines parameters for ListUserFollowing.
type ListUserFollowingParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUserIllustsParams defines parameters for ListUserIllusts.
type ListUserIllustsParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// ClientMode Client emulation mode (Pixiv's `filter` query). Omit (= `for_ios`)
	// to apply the same policy filter as the official iOS client;
	// pass `none` to disable.
	ClientMode *ClientModeQuery `form:"client_mode,omitempty" json:"client_mode,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SubmitDownloadJSONRequestBody defines body for SubmitDownload for application/json ContentType.
type SubmitDownloadJSONRequestBody = SubmitDownloadRequest

// AddBookmarkJSONRequestBody defines body for AddBookmark for application/json ContentType.
type AddBookmarkJSONRequestBody = BookmarkRequest

// AddFollowJSONRequestBody defines body for AddFollow for application/json ContentType.
type AddFollowJSONRequestBody = FollowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with a refresh token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current auth status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// Bulk-remove terminal download jobs from history
	// (DELETE /downloads)
	ClearDownloads(w http.ResponseWriter, r *http.Request, params ClearDownloadsParams)
	// List download jobs (paginated)
	// (GET /downloads)
	ListDownloads(w http.ResponseWriter, r *http.Request, params ListDownloadsParams)
	// Submit a download job
	// (POST /downloads)
	SubmitDownload(w http.ResponseWriter, r *http.Request)
	// Remove a download job from history
	// (DELETE /downloads/{id})
	RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Get a download job
	// (GET /downloads/{id})
	GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Cancel a running download job
	// (POST /downloads/{id}/cancel)
	CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Subscribe to the event stream
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List illusts from followed users
	// (GET /illusts/following)
	ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams)
	// List ranked illusts
	// (GET /illusts/ranking)
	ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams)
	// List recommended illusts
	// (GET /illusts/recommended)
	ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams)
	// Get illust detail
	// (GET /illusts/{id})
	GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Remove an illust bookmark
	// (DELETE /illusts/{id}/bookmark)
	DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get current user's bookmark detail for an illust
	// (GET /illusts/{id}/bookmark)
	GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Bookmark an illust
	// (PUT /illusts/{id}/bookmark)
	AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get ugoira metadata
	// (GET /illusts/{id}/ugoira)
	GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Search illusts
	// (GET /search/illusts)
	SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams)
	// Search users
	// (GET /search/users)
	SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams)
	// Get a user's profile detail
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath, params GetUserParams)
	// List a user's bookmarks
	// (GET /users/{id}/bookmarks)
	ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams)
	// Unfollow a user
	// (DELETE /users/{id}/follow)
	DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// Follow a user
	// (PUT /users/{id}/follow)
	AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// List users followed by a user
	// (GET /users/{id}/following)
	ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams)
	// List illusts by a user
	// (GET /users/{id}/illusts)
	ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in with a refresh token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current auth status
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk-remove terminal download jobs from history
// (DELETE /downloads)
func (_ Unimplemented) ClearDownloads(w http.ResponseWriter, r *http.Request, params ClearDownloadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List download jobs (paginated)
// (GET /downloads)
func (_ Unimplemented) ListDownloads(w http.ResponseWriter, r *http.Request, params ListDownloadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a download job
// (POST /downloads)
func (_ Unimplemented) SubmitDownload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a download job from history
// (DELETE /downloads/{id})
func (_ Unimplemented) RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a download job
// (GET /downloads/{id})
func (_ Unimplemented) GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a running download job
// (POST /downloads/{id}/cancel)
func (_ Unimplemented) CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subscribe to the event stream
// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts from followed users
// (GET /illusts/following)
func (_ Unimplemented) ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ranked illusts
// (GET /illusts/ranking)
func (_ Unimplemented) ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recommended illusts
// (GET /illusts/recommended)
func (_ Unimplemented) ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get illust detail
// (GET /illusts/{id})
func (_ Unimplemented) GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an illust bookmark
// (DELETE /illusts/{id}/bookmark)
func (_ Unimplemented) DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user's bookmark detail for an illust
// (GET /illusts/{id}/bookmark)
func (_ Unimplemented) GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bookmark an illust
// (PUT /illusts/{id}/bookmark)
func (_ Unimplemented) AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ugoira metadata
// (GET /illusts/{id}/ugoira)
func (_ Unimplemented) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search illusts
// (GET /search/illusts)
func (_ Unimplemented) SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search users
// (GET /search/users)
func (_ Unimplemented) SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user's profile detail
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath, params GetUserParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a user's bookmarks
// (GET /users/{id}/bookmarks)
func (_ Unimplemented) ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfollow a user
// (DELETE /users/{id}/follow)
func (_ Unimplemented) DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow a user
// (PUT /users/{id}/follow)
func (_ Unimplemented) AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users followed by a user
// (GET /users/{id}/following)
func (_ Unimplemented) ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts by a user
// (GET /users/{id}/illusts)
func (_ Unimplemented) ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearDownloads operation middleware
func (siw *ServerInterfaceWrapper) ClearDownloads(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ClearDownloadsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearDownloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDownloads operation middleware
func (siw *ServerInterfaceWrapper) ListDownloads(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDownloadsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_since", r.URL.Query(), &params.UpdatedSince, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDownloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitDownload operation middleware
func (siw *ServerInterfaceWrapper) SubmitDownload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitDownload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveDownload operation middleware
func (siw *ServerInterfaceWrapper) RemoveDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDownload operation middleware
func (siw *ServerInterfaceWrapper) GetDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelDownload operation middleware
func (siw *ServerInterfaceWrapper) CancelDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "topics" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topics", r.URL.Query(), &params.Topics, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topics", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFollowingIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListFollowingIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowingIllustsParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFollowingIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRanking operation middleware
func (siw *ServerInterfaceWrapper) ListRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRankingParams

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mode", r.URL.Query(), &params.Mode, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mode", Err: err})
		return
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecommended operation middleware
func (siw *ServerInterfaceWrapper) ListRecommended(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecommendedParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	// ------------- Optional query parameter "include_ranking_illusts" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_ranking_illusts", r.URL.Query(), &params.IncludeRankingIllusts, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_ranking_illusts", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecommended(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIllust operation middleware
func (siw *ServerInterfaceWrapper) GetIllust(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIllust(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBookmark operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookmarkDetail operation middleware
func (siw *ServerInterfaceWrapper) GetBookmarkDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookmarkDetail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBookmark operation middleware
func (siw *ServerInterfaceWrapper) AddBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUgoiraMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUgoiraMetadata(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchIllusts operation middleware
func (siw *ServerInterfaceWrapper) SearchIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchIllustsParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "search_target" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search_target", r.URL.Query(), &params.SearchTarget, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search_target", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_date", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_date", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Optional query parameter "duration" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "duration", r.URL.Query(), &params.Duration, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "duration", Err: err})
		return
	}

	// ------------- Optional query parameter "exclude_ai" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "exclude_ai", r.URL.Query(), &params.ExcludeAi, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exclude_ai", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchUsers operation middleware
func (siw *ServerInterfaceWrapper) SearchUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "duration" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "duration", r.URL.Query(), &params.Duration, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "duration", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserParams

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserBookmarks operation middleware
func (siw *ServerInterfaceWrapper) ListUserBookmarks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserBookmarksParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "max_bookmark_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_bookmark_id", r.URL.Query(), &params.MaxBookmarkId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_bookmark_id", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserBookmarks(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFollow operation middleware
func (siw *ServerInterfaceWrapper) DeleteFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFollow operation middleware
func (siw *ServerInterfaceWrapper) AddFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserFollowing operation middleware
func (siw *ServerInterfaceWrapper) ListUserFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserFollowingParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserFollowing(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListUserIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserIllustsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "client_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_mode", r.URL.Query(), &params.ClientMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_mode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserIllusts(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/downloads", wrapper.ClearDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads", wrapper.ListDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads", wrapper.SubmitDownload)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/downloads/{id}", wrapper.RemoveDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}", wrapper.GetDownload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads/{id}/cancel", wrapper.CancelDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/following", wrapper.ListFollowingIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/ranking", wrapper.ListRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/recommended", wrapper.ListRecommended)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}", wrapper.GetIllust)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/illusts/{id}/bookmark", wrapper.DeleteBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/bookmark", wrapper.GetBookmarkDetail)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/illusts/{id}/bookmark", wrapper.AddBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/ugoira", wrapper.GetUgoiraMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/illusts", wrapper.SearchIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/users", wrapper.SearchUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/bookmarks", wrapper.ListUserBookmarks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/follow", wrapper.DeleteFollow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/follow", wrapper.AddFollow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/following", wrapper.ListUserFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/illusts", wrapper.ListUserIllusts)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbOJbwq5ziN1XjVEuyc/m++jqp+ZHuJD3uSjpZ29mu3lZWhMgjCW0SYAOgZXXK",
	"VfNrH2BrnnCeZAsX3kGJcmQnmdl/EkkAB+d+DoCDj0HE04wzZEoGTz8GGREkRYXC/PuO88uUiMsLsvy3",
	"HMVGP4tRRoJminIWPA3OUCpBIwVz96kExUGtuERQZLnEGNZUrUCtqAS8JpHSj4GRFCfBKKC6j99N16NA",
	"PwyeBoosg1EgoxWmRA+YUvYa2VKtgqcPR4HaZPojPSpbBjc3o+D7hCJTb3iMPTDaDwDTPCH6EaQ8Rjh6",
	"R6/p1Z8lhAuaKBQhGDgeTOBtShUc/QXCBRczymX4YMoUB5JlyQbUCkGSFCHjCY02YBsDkeYNXyxoREkC",
	"9O05RGbcZ1OWESkhZJxhqLETU0nmCU6mrAcDtuFMg9nAxJ8ELoKnwf85rmh2bN/K4woLBikv+JolnMSn",
	"8TuiMdfGSfEefuNzoDEyRRcUBQhUuWAYw3wD4bu35xdwHLtPZVhSLNN9luDSOBgFAn/PqcA4eKpEjvvQ",
	"rwDlHVn2UfDheE4kxpCRJQJlMV73MY/+ooGzGBckT5QZO6WMpnlah4MyhUsUTUBQbIHlVGEqIUNhoHkG",
	"UULSDGNN2PDXhyN4eHLyIewFD8WsH8RHJ6MgJdcOxpOTwRCfK6Jy+ZpK1ScCPE3JWKIWb4UxyHwuUQFf",
	"QNjswzAoZVGSx+gkYcEFMD5lltMn8PKapFmCTyH8Pccc45HIGaNsGVqGRvvazr32ugcj0gzbwEc/i7zP",
	"Yg3+OWVRH3nOXn3/+PHjb0HRFKUiaTaBtyzZaD6XVhWFue1lRhRM85OTx/gXKB5J3XM4ZURgKQoTeC+t",
	"QGgJXwjOFDJDbyNA+qHACJkaK0GiS4ynbE1ZzNdmOJ4rkBExKDDfrlc8QVhRqbjY9OuABkQN9Cy4SIkK",
	"ngb6g7GeZ+AVq1wYbdeDpwua4tjB6XSYJrREIqIVCJR5omQfG8eu78Ha6dx0W4Bk4Ht5bZjsOe0B8OcV",
	"MjC6BNB+Cs9Px0tkaFl4zbWxWQietoCeMqvaIbTPZ4TONHr+8jAslLuZqIIFSbSZKhle0yftJ4kDY0ao",
	"j13nnCdI7NxOkySXqk/3Wuio+cYiBE5f3E63lrxAmfp/T4KdCsMCdrHJerWb+QB0U8cWz2DO1QrqEgFr",
	"TRueUqUJcbReoUCQeZZxoTB+0GvYNTxDOaaC1AJuKXRG2CVlS/tSbuMcQ9uRAdKIXUxoshkL2x4kRgbv",
	"jhTsN4yUBMqM74JTJjDiaYosxhgWqHWA4RvF4RIxg8J1cJob5rgiV5Tnop95HIvNHAQzS365i5PekOvC",
	"CTuN+5R7LiS34qtnyvC67o5ZK+VcELxWs5Rcz4rXMxqHVoZ0y0ygnoXUkpRxJntdtFYXwaew5NvFQmKf",
	"3bIvzdS4+TnOyJIyowASKhUgizNOWb+qss389vZktAXaEy+0hb/bA++/U0nnNKFqAzLiGcJRls8TGmmN",
	"kwl6RRT2iodwXQ8WkQIWA9h7iWK7wsklintSNDe6K8tCNo4g8Rn+nqNU+l9kLKj5qX1qGhkdePyb1MB+",
	"HDj5l0JwN1RLg7ErklDtKxaRzCS4GQU/8e+rYZstnltdIPMoQowxfgaMw5zHG9dQveI5i+8e8jOUPBcR",
	"AuOa5XMWQ6GiDCTvGcnVSrvqkRaAuwfoJw4Wl5aBJEpJOZvA9yRJiuhAg3Sc8CVlISyokMqCmkklkKR3",
	"D6PjbTdeZaIIg5zhdYaR1hWom0+MoLge9YDPc7Wybq8JfQXPUChqWbaD6rZy1p5uRgXKGVG9bhnLk0TH",
	"eoVAtdy0UaCFUmtQn4j1NC7FzLW2Avxx11g3dfH+tTW/D+XnfK5toe68sDsvUBGadDFEZWkD+jBUqrR9",
	"NFkdyuYYtQ63AVxTNU2IbwVOZ5jvEySiiEjkmdNzvtFSfmUx0xKrPJ2jNmg2KIkxQc2jxgwXcUHgtT51",
	"1BTdf/CCWCYDeoxBmfS4ZHwO//jb30GLqeCJBPr2fEyybCzVJkFw0gtLoihbTqaszIqYhAhFWXpDuqFN",
	"XTSTI8+K3IdLfMgpo2oCP5EUYwhryY4QjCepOJArTmOIeJJQrXKKHBKC8f9pNGWMG6XNFzAN7DCULaeB",
	"i0GZtky/Bg5ULUucYQ1VlQCWiZLK3+xBGRFKxxzWN9aw/MbnsCYSIoHGIVloFVMNbj08bSoJW5JgFORL",
	"TgXZCsWPfN5lJNf/Nj3T6ZDGnkh65GDqUzhdBeO+Vw4t24TGg8ibUWBcSlzPcpF4YtBVns4ZoQkcyd9z",
	"InCWYkzzFP7xX/8NtZ8JEUt8MIHnc6mZizMrOBkKSaXG/BwXXDPOikpYUExiwGvzZuLDjSxV/pD5OAOh",
	"NQGRl1bzKUwHt78g8jKo9AgRgmzMf6oS9BKpyk/sEe43tKZWlRWpm2QcVSmXGmM1Ri2m6lMtNU59TX1K",
	"lkSKXuEs4rnP1/oh4XOSgHlr0k82SRTCNxAWeSRL3SPKYsx0CGa/tEL+YDJlLwS9QptvlTTGOREwJ/HS",
	"JVS7TBxzNhweTUmjj3eA4R1Jt9ibQbTMe/jDpAk78L6MVlyDYbNOxs5hDN38KJCFQmGTk1pv7/DYR1Vm",
	"cuuQuFigoa8dStI/cO+RFFfEpwz0Y4vzlKhoVeTLXHLqyHItfNPM1T0YYCkNVYpxR0WKuJaKbbBsg1+2",
	"SUDlOTYn8pouMNpECYIGGTXqCMT1fLsO1Im8rBsLKwbawymzpSUnBqNgQWhifkSERZgkDbvfNSNG53Qk",
	"s4AB49l8o+yzATbA+M4DHMyRtsM4y7wh6IVW4Qr0S62/Y2qn7+mCUbnarvx2wtFj/H7j81nPK83IFVLa",
	"uXPjAY3tIsZIU2/8EOgCcnbJ+JrpeQxAo1REqE+c2G0tl9f6vqKMJIUSgfdnr+HIinJ2TdMlpFTTHQSu",
	"BVUNOdtmdRyO7ZB1jqiZnRqyR12m9Incy4IFW46R18F9Q7TywLFAEmts2uAP9MeTxvpE3oqnPQiPy9in",
	"lZcyP0gCJI6p+2k85WsFRzhZTkZVSDrn8eaBl9lTlNKrcv+ap4S1J+C+3k2IyK4bFr37EPqKJwlf33Gg",
	"9FckSX+AXfFyRRF+uXNyrplvUtbzHJRvT1GRmCgygfMVydAxu4RMf7rkk9Pax6dswTXSW7xHXPcebWL9",
	"qpkWbe/7FdLlSg11wff01d1qx36NdJA9MwHf0HYpWaL26ndqo1P95Xv9oW62O2dA5SzNe3MumnDGbA/3",
	"s96gIu+0IHicLNOdpGxp1NQSh/R1bj4vetStKudyAObqsrXH55SzGVFK0HmuWpPv8Fd7lpIwqjazBK8w",
	"GTisRFH480nydhE8/XXXAp/5/uZD24qZuGk5nFp1ybsgy/0iJ8V5sidujFdYMuVQn8i2smtEar9GOhwe",
	"2sDJsTdruAuR76Xt5IpKOm/gqyZOaxpbb20ANNezvVjX5x1Yyo2KlcCaEhmVCnVUXwgxE3UcVJC3qV8b",
	"ElhMqFSxLd5vTKJkco8aaCiaBuW6HDPqZCkLlNeUWUc9+1Rvr7R3rN0ouB4v+dg97LNa9c/GNM24MKQr",
	"9qLYVgaDmgmCJVWrfD6JeHqsrjMUyXHxSbV0bJPB9aRna+1VkCxzewkIWJQ60wvWmZrAG6+xbfbcNbi0",
	"tO671UeX++zjvfDYmurhcfnOGRzfPPdVmD7V5lvt7VLsHBVwlmzMjq9jLXDy+CONb45LDg/d8vGcRJdA",
	"JITtFWRvBLR79cLA59Znu0ly7Urbl6B4BYCJv3TfOgJjHBa5UCu3GetWcHg5ZZuDWeSIe/K8vri8bdQ6",
	"RC/WcLrmShAmE5PvuN06j2nV7ecWGuXC7Ms8oBCUjmEHHSbh68WHzQr7Y/h6Ctm/j6wRSDQ+L3seucGH",
	"IqicxCFR85ovKdsSnS0EytVM8UtknvwTZ8txQq+wWLd9+zxXK3CtwLSawDkinL18/uLNS6OrV3ytxYzP",
	"FaFsd4jZBMEnK6XX3VVwtwkd2lJa9TGQUCU8h6RTKxzoTJULuqSMJLMSXj9fDp1AbaxDTuMn7gIDX9zM",
	"9MudAbPp4haRsvWgZySKUMqZW4Mc6JDuCrOHR86fKZjVbzcGgzNtgXs/Ktio94PKq+0bylBxz9zAXYe2",
	"ny3GNMzaF1xqpyRx+9WHRWlbwtEvN7Y8WAh5wLDQGwI2Ira6MLTjx0ZQ6CLGRmxYJ20ZWpYxYDuI64Z5",
	"jSiwivFa9GoGfS0J70prWzQHmrNS3x7eEHgdVBLbDP0sz1y2vmAgj665b2d21AfePsg8tHv7TvAFTXDr",
	"bszMftNnVF0XXZNK4lhoeznYwunIaSl4zuKtrsgomFNhFZ//zSwmmy1vN0jEUOOthVJsZsUaTqfHJbK4",
	"wWE1wy5nmcC06eY3LWIuKVvOolwqns4cmu3U/U1+sxtvtqwZDjKYa84L1O5czBO47HOLrEpZmEUaw8n7",
	"mYFaZsnorpndhHybPiobvWfL/drY0HmvFk6t7o8dq29vMTHTcHCTNVUKhfZsCw+qS2b3zVCOWeO8WKTY",
	"T28WDUupKgS9LtYNIS7Zc1RXNi2xtWJTW/T18K2fXm1eafJBC+G72NrPsl5y92jCLrmaxKmLdkP97NI1",
	"Aw1QYSvuwP5sybIMzZS47/aby90kRlzn7wzhqdr0WVdHBciKD2GRkKXcYWjLbrsWdx/rt48p67M7ht/6",
	"NlX32I0W2UpRLyW5V9atGNsx9yNzRYlDktkd8yo2MBeZVgv5GvEyGAUpZ0aBxWQzS4kRHv1zge6P/qwe",
	"LJj/gvNLimUrq2z0b/Hw/9f6qv21/bkHto/Gz6U34XtWC4nK40ZBqa+KCZUP3Nkgb1+ts5M1fKypWlE2",
	"S4hUjqr1Jw5P9UcWZ/2DnDuqVSDHJqZCWYe6/sz8JuZnxrM8IcK+6R/D7gRrIYYIRY36V9FqtuBi5uK3",
	"ElG9H1yTSHUfm4hyRlg8q2LKS9ysuYh7QCu8AZ82sYdKJIQfb0KgTCoksdksqq1waPKnmGZqA9bKPAPK",
	"QK2IgohIhJDGIVAJJ541rfgTcwz90fRAMT4v7OLhhPc8n6dUFZvQerPYja3oAw/I7nu2sLuwo8fzpavf",
	"m735r4QLS1sbJzGxin8ApYqYbzuhnLW3HQ8kVR3EQ9LL9vvGJXi7s1/oEYcn1+pgevJrf9BsUKbVdvMf",
	"NPPm/8teRgV4eyGxnOzd4bF/idx+B0eE0dScG7Gc+aCWY2+vkPu77uoTe8JkltZouRvHJTLaSG73disU",
	"38n6eZM57smxbQ560Om4VFpvnkjmaUrEps99NWd/vWsv26JPl7H8xKUTadZuMjUTlaL3ZmTcEs884ZE5",
	"AN+fP6TShZB2MaMn1B2ScGwEY4PUTid68ZrYIutYBouegZrzGMpjjpIHZy+7mcW/SplVmcoBqKnjNavH",
	"YQPaVtHCnisQpthHRqKdQP5cftjRZjbfn5WhdncS9XG8ToKmjs1Y3MvenWpvzC3PBg9Drx9R2zbC6Hbv",
	"7Mk+j33TGusbILDANUiztduZOLlNgbn++jZ+HQKp21djq/Te8EVE3yiHQnwJUQ3wPdRIQZ9DaxLXr18A",
	"DsO2M3dqdA+nszbhDkk8aK5G8LH3z3Vt4zPKpZoAqs1uD1eX3Xj2RKwIFXtb5RjtsS7vC8Uz/44pzqji",
	"ouddLnv2WeXSLhh0bWrPY6GJ6B/G1L/qeac0O6je3dzeFyX6m4tZ++XEsyiokOMGq0AtASuQVM2wQneB",
	"JkeZkSNrRUQ/qAOFuOLCw4mwRoJm2R7G/o7mcPXY7LNEFsPzd6cTOEMSj+0GUcHXkrKlVu65WsE3ZZWh",
	"Y+vnTKbsHVErMCJrKkbJLKEKSCS4lKCtrYScxSgg1MDK4xDmG4h5Sih7NmVOmoGwGOSKCKxXcQGpyAYi",
	"ZEqQhEqMTbEAd+bXpkcak3j+7jQYBVcopJ3gyeTh5ERzD8+QkYwGT4PHk5PJY4c4I5a1aiZGt3HfcaKX",
	"19GKsKU7gdy7xa7YAr3iQrnteNYFnjL7Xs/SHWGXQBVIFFcoxpLG+MwW6Ps9R6agcUhtysqKRyAwl2gT",
	"TVJxja2iQotBitY3dit4bHYF6klZEUCpvuPx5mDFWRrbFW+agub25zTKAT06OTnY2LUaLp7qMM/ruJvA",
	"xQodERyNqKxQV2LfVLB5YmH0DV3O5bhW18g0ebi7SbuIz80o+L8njwa0KyrqmBo2Nh60ZAXq6mOQJgMW",
	"u2BcsZfgg25ZcjjPVT+LmxInlr+rIgumUyuctvaIK3nKxjGVl+6ws93OcBpjmnFN3ImPEfXYHZZ4shsH",
	"VQ2nLhJ4buu8RbkQWmqcKGxBQnUA0eWjm3D+gKrGW5+Ng7938zEa14I8aU3/B1TltGuf+adeVnN1iU1U",
	"Hi/nhXkuAa9QbGydE1PR153BpxIUitScH9bsYNLvBTu4k7FTFkpXUbQsHGpy5O48v0v+m3LBJEmqDm0r",
	"lJMp+4mzcee5y8ZD+OTkJJzAK2NU3JFyY3MYV6B4Hq0w9inCZvkeo/2rksc9OxCrT477Sq7efLhDFukp",
	"OeStIZbyK40tlzG6V1XW4Mrv8uRybBVFRdx6GQTZqHhU49aKRT+YxVPlO7RitHWzGOAE3grtW1AJDNco",
	"lStIBj+7OqyW9eSUVXxNZVkybATzXGnHZIkhHENYFIgIgSRrspG2APRkygr8Q0SEoI7vzWYDV0ckS3IJ",
	"S1tZJKwXlwjheMrCqr5ECJK7MtESYs7+rIChdhSgKNVre5RlnUOvaadS3QFDjwY3raol79OoXmV5j3bd",
	"GsB3KnrtejcemftR87KpRmkPIX02kdMAtkTsqBSRB70S5vcBzlDypDDy7gRfUY5QiwpNYq130ZQyKeth",
	"wxEX+umU6Sd2BQH+oNmDESAzRU5shzouGjlfwi6u6qc/8rlx0qasmLIW0PDRySN4brLMGIfPrJm3dcZs",
	"3CEhE3wptFt3RcmU6Q/CYo4hKJ7RSMMe/vDyAo7xSiM19ElSc+nyjrxl//roILf50V2wdQ9LA3EYv293",
	"+MkwV9BV5fxE/9kSo1Wgp0dSGu6TOSM5xIcilfXTBueoLOsDx2DL+sAxlGV9HpTVeKfMRCY2aCnL9RsR",
	"p7pXZzch4cuntvJZzSu3FYxFbE92/uNvfweSCCTxZlzVW3HxeL/rdFZse3hy8m0IdFEWvTNRE00ScMWK",
	"zAA1qUxzqaasfX2APVVqZ1rUCoUL7uofWmhGoENaYv5MWUoYWaLwSarxc7Amqbczeq5irseC7BeO3CO3",
	"Pzn59u6rqv7YR2VLPqCqqLlnmM7U/WoKliVQu/LVPh5fJxy7Q2qf3JdivbAiNLlHlunEirdUdk50t2QN",
	"zPsiamT14M34CGZXlJ0+bNMtTlXp70kzLsRuOsEO+r+K4G4VwVaSNDnMEgRIqTYGMpt1y2rpmN5TzaHC",
	"a2W/H1ujHkLEGbM1/Sfw0vRkDJraZDZneoUJz1BC+JHGI1ByZL3CkfliBDFR5CYEdFcazPVMFQqTx5D5",
	"XG6kSWkflUCPTKZlBPbNA2ulC/NHiizHlJlRjFtqODy0/91dQ1V2+5kWAXehwsgKkGursR+jnrgwRlmb",
	"ZTfZ6tqB0g82NTEVYTERMZyfvwSJKdFcJidwurCegYNSIou1HxG+JlKNDc7Gpy9CWCHRQbR2zU2RSU3C",
	"eb5Y6NlYe7Di2vXXIbYAS7WRHdgE5SAwS3S4rFaYOith/Pk81V3pmRQT2hRAwekLWBEJc0QGeGVOxtX7",
	"nDLjLpQwu7oiocX+RKDcsCi0wOiQuvJFpqZGn8kyCRwvUEUrQzkuqCKmkKXNWxYEOnt5flG7VMDjefyA",
	"yjJYV9dsv3PHkrMoZ4mT5aQKUkZ2JuGDyZSVl+6YtJjhl/5rJez7xpUBVTm1Vu+eU/27LWFH1ppKxZuW",
	"OddkcFJot+f5Kgp0dM3bzFDf0NAMNTlQXHyez/U4c7R3k2FjkJpKcirI6qOVqV63LT1s69vdZWq4UUHP",
	"gzGNbxqZINmCu+lo4xVGl0aK9HerAuJixo4x7IzdxgO3mKeJ1Dd5HYW8Kr46Lfcr7Gd6m1dpDMgA1W8K",
	"uVMfrlaex4P0cuLmZph6zuczLP+YcNASwDrXxY4zKA9aOVKX+3katHbX0WyltDuN0SWw92qY9qV1w872",
	"1098aNrWTyCYLRyd9JS7ySfW2psyCH/55Zdfxm/ejF+8CGsXl2lpT4hCqXrvsrIHxiuAM6K06Q+eBv/5",
	"68n42w8fn9yM7Y9H1Y8/+Uqk7MfBuz9v32z4GZm+QPfn53bNseWm6QEMXt3ktJ3Ja9/tq8nat2rdAyfs",
	"brLlxqzPyUcFmu2xji+AnWo3fQ3lqSL11+cYnBYVwW7DRveRpPAWuPPdpVQ/guPK9301qd0fUDUrDw6i",
	"a1n2rpnbbdLY5naL+2YOTugvNuXwKeQoEoKsIMq8Ql+XLP1ZwNa1RF+ukLUA9YhX8cVXKVrFjhPtZ/5Z",
	"ltR0c7EBbEHrHhJnuYfEz+P4kIJ1+PW79jVTN9377v5JRbjk1+2E7ahUd/FRX2rvrLYCbNIFY0VNrigl",
	"jC5QqjIZ9QfNzEUFGYkuyZKy5ZQhiVa2VXVPb7GjwiR9zHbT4oqq4szdlNVPl/bleTqHBb9UVdNz5M6j",
	"ctzhw/Ko4VelcvIm8L3MZ+/9Pa4dHPHy3Ru3bW2+AXc23N7MsnwGErG8PliZA+v2mHd5M425Ql6zZSi5",
	"cC+5iM0tZN1FCnvyvTdR4gtLzVH1T7hW3d9rY0p73t7sDu73983Fvl2aegOe4P41X6OAubkCsx7YGzSb",
	"Qm/GIXULQj3Xigs1O2hs3xIkU+b6U0BEFs/uM/nQvBB8QIPWDd3/1PmN88YV4p9hI9cnbmOx4HcDWCvw",
	"Tb1YlszaqhXtwYaYyiwhG9A8q7WjO/Lap+Leu6Tj51Nwn6KEDi1AX7I4tI/y+XwFc/S8IRhfoUy08+AN",
	"iajK3W/L57x3R4f38v5qF3J/ibSvHQjvI/3XGJWSIh4tKoB1Uj+WH9rkP25U6fUqRnvNfm3P+XzjuQoB",
	"3hEpp2zvq/aByPL2/imLzFh9m701db6rFaa9S8bce5XuDbkuYDuNB7cqmlyQ5dfoPpTUsJ4D9JCfSpCo",
	"YL0yx/94eXGFva5Wfj2iZlLnpJ37kbvFzC5P7s6t2kXWT+Ltf5G86ntmcerI4SFBf6LtUFg+fJKteUHh",
	"v06K7dUOWnrFadcCvqZXuWvhS7MX97arY4DHW23t+OSFyftXx4Ytqv0f881gLuomyvw8dNudPvtx0GdY",
	"Tb9rtqsXDerztotdPF8h5xWgb2U5e+HHVcEypmZHcEwyenz10FDAtSgLW7i9aZqe7ok5xlz7X/Bt7ZEd",
	"rvbAhXu1J9XG49pDt/Xv5sPN/wQAAP//fZ8cGRKVAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
