// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	pixivgo "github.com/txperl/pixivgo"
)

// Defines values for DownloadIllustType.
const (
	DownloadIllustTypeIllust DownloadIllustType = "illust"
	DownloadIllustTypeManga  DownloadIllustType = "manga"
	DownloadIllustTypeUgoira DownloadIllustType = "ugoira"
)

// Valid indicates whether the value is a known member of the DownloadIllustType enum.
func (e DownloadIllustType) Valid() bool {
	switch e {
	case DownloadIllustTypeIllust:
		return true
	case DownloadIllustTypeManga:
		return true
	case DownloadIllustTypeUgoira:
		return true
	default:
		return false
	}
}

// Defines values for DownloadStatus.
const (
	Cancelled DownloadStatus = "cancelled"
	Completed DownloadStatus = "completed"
	Failed    DownloadStatus = "failed"
	Queued    DownloadStatus = "queued"
	Running   DownloadStatus = "running"
)

// Valid indicates whether the value is a known member of the DownloadStatus enum.
func (e DownloadStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for IllustType.
const (
	IllustTypeIllust IllustType = "illust"
	IllustTypeManga  IllustType = "manga"
)

// Valid indicates whether the value is a known member of the IllustType enum.
func (e IllustType) Valid() bool {
	switch e {
	case IllustTypeIllust:
		return true
	case IllustTypeManga:
		return true
	default:
		return false
	}
}

// Defines values for RankingMode.
const (
	Day          RankingMode = "day"
	DayFemale    RankingMode = "day_female"
	DayFemaleR18 RankingMode = "day_female_r18"
	DayMale      RankingMode = "day_male"
	DayMaleR18   RankingMode = "day_male_r18"
	DayManga     RankingMode = "day_manga"
	DayR18       RankingMode = "day_r18"
	Month        RankingMode = "month"
	Week         RankingMode = "week"
	WeekOriginal RankingMode = "week_original"
	WeekR18      RankingMode = "week_r18"
	WeekR18g     RankingMode = "week_r18g"
	WeekRookie   RankingMode = "week_rookie"
)

// Valid indicates whether the value is a known member of the RankingMode enum.
func (e RankingMode) Valid() bool {
	switch e {
	case Day:
		return true
	case DayFemale:
		return true
	case DayFemaleR18:
		return true
	case DayMale:
		return true
	case DayMaleR18:
		return true
	case DayManga:
		return true
	case DayR18:
		return true
	case Month:
		return true
	case Week:
		return true
	case WeekOriginal:
		return true
	case WeekR18:
		return true
	case WeekR18g:
		return true
	case WeekRookie:
		return true
	default:
		return false
	}
}

// Defines values for Restrict.
const (
	Private Restrict = "private"
	Public  Restrict = "public"
)

// Valid indicates whether the value is a known member of the Restrict enum.
func (e Restrict) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for SearchSort.
const (
	DateAsc     SearchSort = "date_asc"
	DateDesc    SearchSort = "date_desc"
	PopularDesc SearchSort = "popular_desc"
)

// Valid indicates whether the value is a known member of the SearchSort enum.
func (e SearchSort) Valid() bool {
	switch e {
	case DateAsc:
		return true
	case DateDesc:
		return true
	case PopularDesc:
		return true
	default:
		return false
	}
}

// Defines values for SearchTarget.
const (
	ExactMatchForTags   SearchTarget = "exact_match_for_tags"
	Keyword             SearchTarget = "keyword"
	PartialMatchForTags SearchTarget = "partial_match_for_tags"
	TitleAndCaption     SearchTarget = "title_and_caption"
)

// Valid indicates whether the value is a known member of the SearchTarget enum.
func (e SearchTarget) Valid() bool {
	switch e {
	case ExactMatchForTags:
		return true
	case Keyword:
		return true
	case PartialMatchForTags:
		return true
	case TitleAndCaption:
		return true
	default:
		return false
	}
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	Authenticated bool       `json:"authenticated"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	UserId        *int64     `json:"user_id,omitempty"`
	UserName      *string    `json:"user_name,omitempty"`
}

// BookmarkDetail defines model for BookmarkDetail.
type BookmarkDetail struct {
	IsBookmarked bool     `json:"is_bookmarked"`
	Restrict     Restrict `json:"restrict"`
}

// BookmarkRequest defines model for BookmarkRequest.
type BookmarkRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// DownloadIllustType Pixiv artwork type the job was created for.
type DownloadIllustType string

// DownloadJob defines model for DownloadJob.
type DownloadJob struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	IllustId  int64     `json:"illust_id"`

	// IllustType Pixiv artwork type the job was created for.
	IllustType DownloadIllustType `json:"illust_type"`

	// Status Lifecycle state of a download job or task.
	Status    DownloadStatus `json:"status"`
	Tasks     []DownloadTask `json:"tasks"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// DownloadJobList defines model for DownloadJobList.
type DownloadJobList struct {
	Jobs []DownloadJob `json:"jobs"`
}

// DownloadStatus Lifecycle state of a download job or task.
type DownloadStatus string

// DownloadTask defines model for DownloadTask.
type DownloadTask struct {
	DownloadedBytes int64   `json:"downloaded_bytes"`
	Error           *string `json:"error,omitempty"`

	// FilePath Target path on disk.
	FilePath   string     `json:"file_path"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Id         string     `json:"id"`
	JobId      string     `json:"job_id"`

	// SizeBytes Content-Length, or -1 if unknown.
	SizeBytes int64      `json:"size_bytes"`
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Lifecycle state of a download job or task.
	Status DownloadStatus `json:"status"`

	// Url Final request URL (after pximg mirror rewrite).
	Url string `json:"url"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code.
	Code string `json:"code"`

	// Detail Optional additional context (e.g., upstream body).
	Detail *string `json:"detail,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// FollowRequest defines model for FollowRequest.
type FollowRequest struct {
	Restrict *Restrict `json:"restrict,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// Illust Pixiv illustration metadata. Shape mirrors pixivgo.IllustrationInfo.
type Illust = pixivgo.IllustrationInfo

// IllustDetailResponse Wrapper for a single illust detail. Mirrors pixivgo.IllustDetailResponse.
type IllustDetailResponse = pixivgo.IllustDetailResponse

// IllustPage defines model for IllustPage.
type IllustPage struct {
	Illusts []Illust `json:"illusts"`

	// NextMaxBookmarkId Set only by `/users/{id}/bookmarks`; pass back as `max_bookmark_id`.
	NextMaxBookmarkId *int64 `json:"next_max_bookmark_id,omitempty"`

	// NextOffset Next offset to pass back, or null if no further page.
	NextOffset *int64 `json:"next_offset,omitempty"`
}

// IllustType defines model for IllustType.
type IllustType string

// IllustrationTag defines model for IllustrationTag.
type IllustrationTag = pixivgo.IllustrationTag

// ImageUrls defines model for ImageUrls.
type ImageUrls = pixivgo.ImageUrls

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// RefreshToken Long-lived Pixiv OAuth refresh token. See README for how to obtain.
	RefreshToken string `json:"refresh_token"`
}

// MetaPage defines model for MetaPage.
type MetaPage = pixivgo.MetaPage

// MetaSinglePage defines model for MetaSinglePage.
type MetaSinglePage = pixivgo.MetaSinglePage

// Novel Pixiv novel metadata. Shape mirrors pixivgo.NovelInfo.
type Novel = pixivgo.NovelInfo

// NovelTag defines model for NovelTag.
type NovelTag = pixivgo.NovelTag

// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
type Profile = pixivgo.Profile

// ProfileImageUrls defines model for ProfileImageUrls.
type ProfileImageUrls = pixivgo.ProfileImageUrls

// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
type ProfilePublicity = pixivgo.ProfilePublicity

// RankingMode defines model for RankingMode.
type RankingMode string

// Restrict defines model for Restrict.
type Restrict string

// SearchSort defines model for SearchSort.
type SearchSort string

// SearchTarget defines model for SearchTarget.
type SearchTarget string

// Series Pixiv returns `{}` instead of `null` for empty series; in that case `id` is 0.
type Series = pixivgo.Series

// SubmitDownloadRequest defines model for SubmitDownloadRequest.
type SubmitDownloadRequest struct {
	// IllustId Pixiv illustration ID.
	IllustId int64 `json:"illust_id"`
}

// UgoiraFrame defines model for UgoiraFrame.
type UgoiraFrame = pixivgo.UgoiraFrame

// UgoiraMetadata defines model for UgoiraMetadata.
type UgoiraMetadata = pixivgo.UgoiraMetadata

// UgoiraMetadataResponse Ugoira (animated illust) metadata. Mirrors pixivgo.UgoiraMetadataResponse.
type UgoiraMetadataResponse = pixivgo.UgoiraMetadataResponse

// UgoiraZipUrls defines model for UgoiraZipUrls.
type UgoiraZipUrls = pixivgo.UgoiraZipUrls

// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
type User = pixivgo.UserInfo

// UserDetailPage defines model for UserDetailPage.
type UserDetailPage struct {
	// Profile Pixiv user profile. Shape mirrors pixivgo.Profile.
	Profile Profile `json:"profile"`

	// ProfilePublicity Pixiv profile publicity flags. Shape mirrors pixivgo.ProfilePublicity.
	ProfilePublicity ProfilePublicity `json:"profile_publicity"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`

	// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
	Workspace Workspace `json:"workspace"`
}

// UserIllustsPage defines model for UserIllustsPage.
type UserIllustsPage struct {
	Illusts    []Illust `json:"illusts"`
	NextOffset *int64   `json:"next_offset,omitempty"`

	// User Pixiv user summary. Shape mirrors pixivgo.UserInfo.
	User User `json:"user"`
}

// UserPreview User + a few sample illusts. Shape mirrors pixivgo.UserPreview.
type UserPreview = pixivgo.UserPreview

// UserPreviewPage defines model for UserPreviewPage.
type UserPreviewPage struct {
	NextOffset   *int64        `json:"next_offset,omitempty"`
	UserPreviews []UserPreview `json:"user_previews"`
}

// Workspace Pixiv workspace info. Shape mirrors pixivgo.Workspace.
type Workspace = pixivgo.Workspace

// DownloadIdPath defines model for DownloadIdPath.
type DownloadIdPath = string

// IllustIdPath defines model for IllustIdPath.
type IllustIdPath = int64

// IllustTypeQuery defines model for IllustTypeQuery.
type IllustTypeQuery = IllustType

// MaxBookmarkIdQuery defines model for MaxBookmarkIdQuery.
type MaxBookmarkIdQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// RestrictQuery defines model for RestrictQuery.
type RestrictQuery = Restrict

// UserIdPath defines model for UserIdPath.
type UserIdPath = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// Upstream defines model for Upstream.
type Upstream = Error

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// Topics Comma-separated topic filter (e.g. `download,system`).
	// Omit for all topics.
	Topics *string `form:"topics,omitempty" json:"topics,omitempty"`
}

// ListFollowingIllustsParams defines parameters for ListFollowingIllusts.
type ListFollowingIllustsParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRankingParams defines parameters for ListRanking.
type ListRankingParams struct {
	Mode *RankingMode `form:"mode,omitempty" json:"mode,omitempty"`

	// Date Ranking date in `YYYY-MM-DD`. Omit for the latest.
	Date *string `form:"date,omitempty" json:"date,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRecommendedParams defines parameters for ListRecommended.
type ListRecommendedParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchIllustsParams defines parameters for SearchIllusts.
type SearchIllustsParams struct {
	Word         string        `form:"word" json:"word"`
	SearchTarget *SearchTarget `form:"search_target,omitempty" json:"search_target,omitempty"`
	Sort         *SearchSort   `form:"sort,omitempty" json:"sort,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Word string `form:"word" json:"word"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUserBookmarksParams defines parameters for ListUserBookmarks.
type ListUserBookmarksParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// MaxBookmarkId Cursor for the next bookmarks page; pass `next_max_bookmark_id` from the previous response.
	MaxBookmarkId *MaxBookmarkIdQuery `form:"max_bookmark_id,omitempty" json:"max_bookmark_id,omitempty"`
}

// ListUserFollowingParams defines parameters for ListUserFollowing.
type ListUserFollowingParams struct {
	// Restrict Visibility scope (public or private).
	Restrict *RestrictQuery `form:"restrict,omitempty" json:"restrict,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUserIllustsParams defines parameters for ListUserIllusts.
type ListUserIllustsParams struct {
	// Type Illust type filter; both are returned when omitted (where supported).
	Type *IllustTypeQuery `form:"type,omitempty" json:"type,omitempty"`

	// Offset Offset for offset-paginated list endpoints.
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SubmitDownloadJSONRequestBody defines body for SubmitDownload for application/json ContentType.
type SubmitDownloadJSONRequestBody = SubmitDownloadRequest

// AddBookmarkJSONRequestBody defines body for AddBookmark for application/json ContentType.
type AddBookmarkJSONRequestBody = BookmarkRequest

// AddFollowJSONRequestBody defines body for AddFollow for application/json ContentType.
type AddFollowJSONRequestBody = FollowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with a refresh token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current auth status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// List download jobs
	// (GET /downloads)
	ListDownloads(w http.ResponseWriter, r *http.Request)
	// Submit a download job
	// (POST /downloads)
	SubmitDownload(w http.ResponseWriter, r *http.Request)
	// Remove a download job from history
	// (DELETE /downloads/{id})
	RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Get a download job
	// (GET /downloads/{id})
	GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Cancel a running download job
	// (POST /downloads/{id}/cancel)
	CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath)
	// Subscribe to the event stream
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List illusts from followed users
	// (GET /illusts/following)
	ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams)
	// List ranked illusts
	// (GET /illusts/ranking)
	ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams)
	// List recommended illusts
	// (GET /illusts/recommended)
	ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams)
	// Get illust detail
	// (GET /illusts/{id})
	GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Remove an illust bookmark
	// (DELETE /illusts/{id}/bookmark)
	DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get current user's bookmark detail for an illust
	// (GET /illusts/{id}/bookmark)
	GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Bookmark an illust
	// (PUT /illusts/{id}/bookmark)
	AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Get ugoira metadata
	// (GET /illusts/{id}/ugoira)
	GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath)
	// Search illusts
	// (GET /search/illusts)
	SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams)
	// Search users
	// (GET /search/users)
	SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams)
	// Get a user's profile detail
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// List a user's bookmarks
	// (GET /users/{id}/bookmarks)
	ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams)
	// Unfollow a user
	// (DELETE /users/{id}/follow)
	DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// Follow a user
	// (PUT /users/{id}/follow)
	AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath)
	// List users followed by a user
	// (GET /users/{id}/following)
	ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams)
	// List illusts by a user
	// (GET /users/{id}/illusts)
	ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in with a refresh token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current auth status
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List download jobs
// (GET /downloads)
func (_ Unimplemented) ListDownloads(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a download job
// (POST /downloads)
func (_ Unimplemented) SubmitDownload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a download job from history
// (DELETE /downloads/{id})
func (_ Unimplemented) RemoveDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a download job
// (GET /downloads/{id})
func (_ Unimplemented) GetDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a running download job
// (POST /downloads/{id}/cancel)
func (_ Unimplemented) CancelDownload(w http.ResponseWriter, r *http.Request, id DownloadIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subscribe to the event stream
// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts from followed users
// (GET /illusts/following)
func (_ Unimplemented) ListFollowingIllusts(w http.ResponseWriter, r *http.Request, params ListFollowingIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ranked illusts
// (GET /illusts/ranking)
func (_ Unimplemented) ListRanking(w http.ResponseWriter, r *http.Request, params ListRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recommended illusts
// (GET /illusts/recommended)
func (_ Unimplemented) ListRecommended(w http.ResponseWriter, r *http.Request, params ListRecommendedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get illust detail
// (GET /illusts/{id})
func (_ Unimplemented) GetIllust(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an illust bookmark
// (DELETE /illusts/{id}/bookmark)
func (_ Unimplemented) DeleteBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user's bookmark detail for an illust
// (GET /illusts/{id}/bookmark)
func (_ Unimplemented) GetBookmarkDetail(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bookmark an illust
// (PUT /illusts/{id}/bookmark)
func (_ Unimplemented) AddBookmark(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ugoira metadata
// (GET /illusts/{id}/ugoira)
func (_ Unimplemented) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request, id IllustIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search illusts
// (GET /search/illusts)
func (_ Unimplemented) SearchIllusts(w http.ResponseWriter, r *http.Request, params SearchIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search users
// (GET /search/users)
func (_ Unimplemented) SearchUsers(w http.ResponseWriter, r *http.Request, params SearchUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user's profile detail
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List a user's bookmarks
// (GET /users/{id}/bookmarks)
func (_ Unimplemented) ListUserBookmarks(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserBookmarksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfollow a user
// (DELETE /users/{id}/follow)
func (_ Unimplemented) DeleteFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow a user
// (PUT /users/{id}/follow)
func (_ Unimplemented) AddFollow(w http.ResponseWriter, r *http.Request, id UserIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users followed by a user
// (GET /users/{id}/following)
func (_ Unimplemented) ListUserFollowing(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserFollowingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List illusts by a user
// (GET /users/{id}/illusts)
func (_ Unimplemented) ListUserIllusts(w http.ResponseWriter, r *http.Request, id UserIdPath, params ListUserIllustsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDownloads operation middleware
func (siw *ServerInterfaceWrapper) ListDownloads(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDownloads(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitDownload operation middleware
func (siw *ServerInterfaceWrapper) SubmitDownload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitDownload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveDownload operation middleware
func (siw *ServerInterfaceWrapper) RemoveDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDownload operation middleware
func (siw *ServerInterfaceWrapper) GetDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelDownload operation middleware
func (siw *ServerInterfaceWrapper) CancelDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id DownloadIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "topics" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topics", r.URL.Query(), &params.Topics, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topics", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFollowingIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListFollowingIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowingIllustsParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFollowingIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRanking operation middleware
func (siw *ServerInterfaceWrapper) ListRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRankingParams

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mode", r.URL.Query(), &params.Mode, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mode", Err: err})
		return
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecommended operation middleware
func (siw *ServerInterfaceWrapper) ListRecommended(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecommendedParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecommended(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIllust operation middleware
func (siw *ServerInterfaceWrapper) GetIllust(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIllust(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBookmark operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookmarkDetail operation middleware
func (siw *ServerInterfaceWrapper) GetBookmarkDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookmarkDetail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBookmark operation middleware
func (siw *ServerInterfaceWrapper) AddBookmark(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUgoiraMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetUgoiraMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IllustIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUgoiraMetadata(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchIllusts operation middleware
func (siw *ServerInterfaceWrapper) SearchIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchIllustsParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "search_target" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search_target", r.URL.Query(), &params.SearchTarget, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search_target", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchIllusts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchUsers operation middleware
func (siw *ServerInterfaceWrapper) SearchUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams

	// ------------- Required query parameter "word" -------------

	if paramValue := r.URL.Query().Get("word"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "word"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", r.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "word", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserBookmarks operation middleware
func (siw *ServerInterfaceWrapper) ListUserBookmarks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserBookmarksParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "max_bookmark_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_bookmark_id", r.URL.Query(), &params.MaxBookmarkId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_bookmark_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserBookmarks(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFollow operation middleware
func (siw *ServerInterfaceWrapper) DeleteFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFollow operation middleware
func (siw *ServerInterfaceWrapper) AddFollow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFollow(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserFollowing operation middleware
func (siw *ServerInterfaceWrapper) ListUserFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserFollowingParams

	// ------------- Optional query parameter "restrict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "restrict", r.URL.Query(), &params.Restrict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restrict", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserFollowing(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserIllusts operation middleware
func (siw *ServerInterfaceWrapper) ListUserIllusts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserIllustsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserIllusts(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads", wrapper.ListDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads", wrapper.SubmitDownload)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/downloads/{id}", wrapper.RemoveDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}", wrapper.GetDownload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads/{id}/cancel", wrapper.CancelDownload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/following", wrapper.ListFollowingIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/ranking", wrapper.ListRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/recommended", wrapper.ListRecommended)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}", wrapper.GetIllust)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/illusts/{id}/bookmark", wrapper.DeleteBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/bookmark", wrapper.GetBookmarkDetail)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/illusts/{id}/bookmark", wrapper.AddBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/illusts/{id}/ugoira", wrapper.GetUgoiraMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/illusts", wrapper.SearchIllusts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/users", wrapper.SearchUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/bookmarks", wrapper.ListUserBookmarks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}/follow", wrapper.DeleteFollow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/follow", wrapper.AddFollow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/following", wrapper.ListUserFollowing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}/illusts", wrapper.ListUserIllusts)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w97XLbuHavcoa9MzeZS0lObtrpdX4lm2Svd5KNayfd2a5TCSKPJMQkwAVAy9qMZ/oQ",
	"fcI+SQcf/AYlypGd+Lb/JBIfB+f7HACHX4KIpxlnyJQMjr8EGREkRYXC/HvF1yzhJD6JT4la6ScxykjQ",
	"TFHOguPyPXzmc6AxMkUXFAUIVLlgGMN8A7PT9+cfYBK7pnI2DsKA6t6ZHjMMGEkxOA5oHISBwN9zKjAO",
	"jpXIMQxktMKU6IlTyt4iW2oonoSB2mS6j1SCsmVwcxMGJ0mSS9UH6Cm9pldATRtB9EM4eXU7QBZcpETp",
	"dkz9y7Mg1JDRNE/rcFGmcImiBtiHTYb/lqPYdGGzDUB3hQVNFIrnMOdqBURghcn1ChnwlCqFMTxar1Ag",
	"yDzLuFAYPy6X8ruZo1yLgacO/Z8ELoLj4J8mFdkn9q2cVJAawN+R65ecX6ZEXJ7EPbD/kAvJBSy4ALVC",
	"YHitYO46ScjIEp9DRqSEmX41Tcn1tHg9pfEMFoKnpmcm8IryXIJAmXEmsW9FrSGCryHN+8VCoupZmn1p",
	"lsbNz1FGlpQRjf+ESgXI4oxTpmQfqLZbA8IYFyRPVHB8FG6B9sgL7Rlqdo/64P13KumcJlRtQEY8Q3iU",
	"5fOERsAFZIJeEYW9bCLc0INZpYDFAPZRotgueLlEcU8Cd6OHsixkVNhLEp/h7zlKpf9FnClk5ifJsoRG",
	"RhdMPksN7JeBi38tBHdTtSSZXZGExlAp0XFwEwY/8x+qaZs9XkRGF8k8ihBjjJ8D4zDn8cZ1VG94zuK7",
	"h/wMJc9FhMC4ZvmcxcAZGOIZSD4ykquV1u+RFoC7B+hnDhaXloEkSkk5G8MPJEkKk6JBmiR8SdkMFlRI",
	"ZUHNpBJI0ruH0fG2m69S1YRBzvA6w0jrCtTdx0ZQ3Ih6whe5Wp0ronJrdQXPUChqWbaDasfkc84TJEwv",
	"Eq8zKlBOiWpISEwUjhRNtc5neZKQeYKFQLVMZhhoodQa1CdiPZ1LMXO9rQB/2TXXTV28f2ut71PZnM8/",
	"o1YpYVDYnVeoCE26GKKytAF9GCpV2j6arA5lc47agNsArqmaJsS3AqczTemPVZa6R+MSodZcXFqvQhtY",
	"7aGtiYRIoDFhC82UYYBMK9LfAusaaeVK2JIEYZAvORWkttiKcQoofuLz7kLd+Ns4szMgrdOw9tjA1Mei",
	"XZZ07ZVDyzY0exCp5bMUyCF9nfhqOhF5aflSYTq4/wciL4OKykQIsjH/qUrQi5A8i/fEbZunNSNXaG2i",
	"rFx/WCdiY9ZiqZ+28OZPfP6W+kTgM5/vjyTNYx0ctVZlBt4GUqVom6Lyli4w2kQJgl45Al8Agbge02i/",
	"lsjLuqT8nmNuFULOmEZyaEKoBJV5uiA0MT8iwiJMkoaG68qQYYIOqgoYMJ7ON8o+GyAAxtQM0MdhsKAJ",
	"TjOvx/aBiCUq0C+1DxBTu3zPEIzK1XZu3AlHj+R/5vNpzytJ/8AKKa1oxJr7kQ0UQ0290ROgC8jZJeNr",
	"ptcxAI1SEaG+cmG3VSW5SLrrekMZSUBY2wIfz97CI7JQKCC7pukSUqrpDgLXgjonf4AacDi2U9Y5oqYH",
	"asgOu0zpE7nXBQu2rAKPPabqHYlWlOFIIIk1Nq2vBLqxkbhrouUqOA7ylvvpQXhcugqtMM78IAmQOKbu",
	"p3ELrxU8wvFyHFYenHa8H3uZPUUpydKzhL/nKWHtBbjWuwlh0FKN7kPoG54kfH3HfsXfkST9/mjFyxVF",
	"+OXOxbluvkVZszsoTZOiIjFRZAznK5KhY3YJmW665OOTWuMTtuAa6S3eI254jzaxhm6qRdv7foV0uVJD",
	"/Y89HRVCS19leCftk06l2iSD+6VkidNcJDu10Ylu+VE31N12u9hUTtO8N0TRhJtmZInDjf47VORUC4LH",
	"KzLDScqWRk0tcchY56Z5MaLuNY14zobSsy5bezSnnE2JUoLOc9VafIe/2quUhFG1mSZ4hcnAaSWKIm5M",
	"kveL4Pi37Yg5t+1vPrWtmHFkl8OpVZe8D2S5nyurOE/2xI3iiiQlUw71iWyviKdpkeIe3OmK4npoByfH",
	"3iB7FyI/SjvIFZV03sBXTZzWNLbe2gBorqd7sa7PO7CUC4sEck2JhKVCDet5Q7NQx0EFeZv6tSGBxYJK",
	"Fdvi/cYiSib3qIGGomlQrssxYSeoL1BeU2Yd9exTvb3S3rF2YXA9WvKRe9hnterNRjTNuDCkcwlS18tg",
	"UDNBsKRqlc/HEU8n6jpDkUyKJtWOg82dnLlcaNfW/iJIlqHN3ROwKHWmF6wzNYZ3XmPbHLlrcGlp3Xer",
	"jy732cd74bG11MPj8tQZHN8691WYPtXm2xzpUuwcFXCWbMyu2kQLnJx8ofHNpOTwmdttmZPoEoiEWXvD",
	"xRsB7U72GfjcdkYHrJ+1K21fguIVACb+0mPrCIxxWORCrXTQ4lzjveHwcso2B7NIkPUkuXxxeduodYhe",
	"pDy75koQJhOTKbldWtT06o5zC42iAT+oEJSOYQcdCRFLPz5SjGme+mP433MicNrboh1INJqXI4du8qEI",
	"KhdxSNS85UvKtkRnC4FyNVX8Epkn/8TZcpTQKyy2Od6/yNUKXC8wvcZwjghnr1+8evfa6OoVX2sx43NF",
	"KNsdYjZB8MlK6XV3FdxtQoe2lFZjDCRUCc8h6dQKBzpL5YIuKSPJtITXz5dDF1Cb65DL+Jm7wMAXNzP9",
	"cmfAbIa4RaRsPegpiSKUchpxpgQfGqPsCrOHR87fKJjVbzcGg1NtgXsbFWzU26DyavumMlTcMzdw16Ht",
	"N4sxDbP2BZfaKUncmaBhUdqWcPT7jS0PFkIeMCz0hoCNiK0uDO34sREUuoixERvWSVuGlmUM2A7iumFe",
	"IwqsYrwWvZpBX0vCu9LaFs2B5qzUt4c3BF4HlcQ2Qz/NM5etLxjIo2vu25kN+8DbB5mHdm9PBV/QBLce",
	"Xspsmz6j6obomlQSx0Lby8EWTkdOS8FzFm91RcJgToVVfP4305hstrzdIBFDjbcWSrGZFns4nRGXyOIG",
	"h9UMu5xmAtOmm9+0iLmkbDmNcql4OnVotkv3d/lsTx1s2TMcZDDXnBeo3bmZJ3DZ5xZZlbIwmzSGk/cz",
	"A7XMktFdU3tm7zZjVDZ6z5779bGh8149nFrdHztW395iYabj4C5rqhQK7dkWHlSXzK7NUI5Z47zYpNhP",
	"bxYdS6kqBL0u1g0hLtkzrCublthasalt+nr41k+vNq80+aCF8F1s7WdZL7l7NGGXXE3i1EW7oX526ZqB",
	"BqiwFXdgf7ZkWYZmSly7/dZyN4kRN/ipITxVmz7r6qgAWdEQFglZyh2Gthy2a3H3sX77mLI+u2P4re8M",
	"Yo/daJGtFPVSkntl3YqxnXM/MleUOCSZzwi7pGz5zvkGRabVQr5GvAzCIOXMKLCYbKYpMcKjfy7Q/dHN",
	"6sGC+S84v6RY9rLKRv8WT/61Nlbtrx3PPbBjNH4uvQnfs1pIVJ7OD0p9VSyofOCO0nvHOkciotW5Q2g1",
	"WmzCHZT1AevPzG9ifmY8yxMi7Jv+OewhrRbMRChqNLOKVtMFF1MXWpVr6G1wTSLVfWyCvSlh8bQK9y5x",
	"s+Yi7gGtMNQ+QbfHoyXMvtzMgDKpkMTAFzDTBnJmUpuYZmoD1gA8B8pArYiCiEiEGY1nQCUcebab4q8M",
	"//sD3YESdl6YrMPJ1Xk+T6kqzof1JpgbR2QHXnna95ZMd89Fz+fLJH80Z4bfCBcxts40YmJ18gBKFeHY",
	"dkI5Q2wHHkiqOoiHpJcd953LvXZXv9AzDs971cH0pL7+oNmgJKgd5j9o5k3Nl6OEBXh7IbFc7N3hsX/3",
	"2raDR4TR1Jxnt5z5uJb+bm9e+4fu6hN78n2a1mi5G8clMtpIbo92KxTfydZ2kznuyedsTnrQ5bgsV28K",
	"R+ZpSsSmz7M0t9i82yLbAkOXTPzKXQ1ptlUyNRWVovcmS9zuyzzhkXa7tqT2qHTRnd1n6IlCh+QCG3HS",
	"ILXTCSy8JrZICJZxnGei5jqG8pij5MHZy54z8W8gZlUScQBq6njN6iHSgL6VI7/n5sCai0uZkWgnkL+U",
	"DTvazKbiszIK7i6iPo/XSdDUscmEezlWUx1bueUtt2Ho9SNq2xkV3e9UYLET1LJvWmP9BQgscA3SnLp2",
	"Jk5uU2BuvL4zWYdA6vaN0irzNnx/zzfLoRBfQlQDfA81UtDn0JrEjesXgMOw7TSzc+zhdNYWvOvOVXMG",
	"H3v/Utc2PqNcqgmg2uz2cHU5jOe4wopQsbdVjtHeuPK+UDzzH2bijCouet7lsucIVC5tLr9rU3seC01E",
	"/zQyIoz1vFOaHVTvQWvvixL9zX2m/dLVWRRUyHGTVaCWgBVIqlZYobtAk6NM6MhaEdEP6kAhrrjwcCKs",
	"kaBZtoexX9Icrv5qjkAii+HF6ckYzpDEI3t2U/C1pGyplXuuVvCXsl7GxPo54wt2StQKjMiaGiAyS6gC",
	"EgkuJWhrKyFnMQqYaWDlZAbzDcQ8JZQ9v2BOmoGwGOSKCKzXIwCpyAYiZEqQhEqMYYUCxxesTHk0F/Hi",
	"9CQIgysU0i7waPxkfKS5h2fISEaD4+Cv46PxXx3ijFjW7uUb3cZ9N31eX0crwpYozeXk3tNvxenkFRfK",
	"nZSzLvAFs+/1KjMNnlQSqAKJ4grFSNIYn4PM51I71ExB4/7YBStrd4DAXKJNNEnFNbaKWgMGKVrf2FPa",
	"sTmwpxdlRQClesnjzcHKDDROEt40Bc0dnWkUtnh6dHSwuWvVCDx1Dl7UcTeGDyt0RHA0orJCXYl9U4vh",
	"mYXRN3W5lkmtQofp8mR3l3Y5ipsw+OejpwP6FbUhTDUGGw9asgJlsKZqBaTJgMUBFVe2IPike5YcznPV",
	"z+I/JEiE5W/HoRjbQa1wCkz5lRMAzkYxlZfuHrI9aXASY5pxTdyxjxH13B2WeLYbB1U1ki4SeK4MOFEu",
	"hJYaJwpbkFDdDXT56CacP6Kq8dY34+Af3HqMxrUgj1vL/xFVuexaM//Sy2JWtYW3D8WvUaqiLEmHfFSW",
	"ud07RUv7Ur4HNz/xuTQFjca3F78mI1GpGrfo60isMPdJ+ztewTlDyZNCMtyNlKIaTQjznCaxBM7QXM3X",
	"smWuFMAjLvTTC6af2LQb/EGzxyEgM5f27YDamQidANodCf30Jz43mu2CFcvUam329OgpvDCpGYxnz61s",
	"JFTziDXWEjLBl0LrwitKLphuMCvWOAPFMxpp2Gc/vv4AE7zSiJz5LEsz339HJsa/qTDI1jy9C5bsYUcg",
	"DuP3bUOeDdOfrijTVxodS4xWwYkeSWnoHHPnx+2ooPKEV6/McwkEFIrU1A74zOfwqCxTAROwZSpgAmWZ",
	"isdlMbYLZsy5tfRliT8j1lSPuqL6/QYSvjwGtaKybsq0AEVcxPam0v/8138DSQSSeDOq6gc4J9ZVlzA+",
	"LuMKFM+jFcbjC3ZW7BU+O/rbDOiirGBjXA2aJOCKb5gJalKZ5lJdsHbJQXtLyq60KBUFHzhYBFpoQtB+",
	"IDF/LlhKGFmi8EnqmVlrTVLrJRN7zkVXTSatkoo3n77Sht8jtz87+tvdF9X6qY/Klnzax5/jgpvSiCm/",
	"omzZtuSWQO1KLoa5Hef22qM+H+YOqX10X4r1gxWh8T2yTMfBuqWyc6K7xdU27yXgFYoNMM5GpeYzPoI5",
	"SmCXD9t0i1NVun1NeRqnvOvE2Un/XxHcrSLYSpImh1mC6AjOqY2BzGbdsl5XvnZLb6bwWtn2I2vUZxBx",
	"xtDcAx/DazOSMWhqk9lEwxUmPEMJsy80DkHJ0HqFoWkRQkwUuZkBusquc71ShYKR5ILJfC430uSBHpVA",
	"hyY8CcG+eWytdGH+yMaVkL1gZhbjlhoOn9n/MzClP6uU0HMtAq6ubGgFyPXV2I9RL1wYo6zNslsszHFF",
	"rijPRekH6zmkIiwmIobz89cgMSWay+QYThbWM3BQSmSx9iNmb4lUI4Oz0cmrGayQxCiMa65HE5qE83yx",
	"0Kux9mDFtevPcI0CLNVCO7HJO4DALCEbA0vqrITx5/NUD6VXUixoUwAFJ69gRSTMERnglbnpUR/zghl3",
	"oYTZ3ZOfWeyPBcoNi2YWGJC85otcmJpTEhQHgaMFqmhlKMcFVURpWGywXxDo7PX5h1pNWY/n8SMqy2Bd",
	"XdOug5WmZCRRN7JJB01Oyxi26FEVpIR2JbPH4wv2XjukJuOWJLaTg8NbWti8b1SMrcoDtUb33FLdbQk7",
	"stZUKu278SbzdK7J4KTQnmnx3ZDt6Jr3maG+oaGZ6lCx8Hk+1/PMUbOBpnJ9kppKcirI6qOVqca0Ladi",
	"6zXdZeKgURHKgzGNbxqZINmCu+lo4xVGl0aKdLtVAXGxYscYdsVut85lwDWR+havo5A3RauTcpNvP9Pb",
	"rKR8E+7sUC8Ufac+XK3chAfp5cJhgSatv8TxN8uZmnDQEsA618UxDSgvDjhSl5vgDVoLe3J4K6Xd6eIu",
	"gb2Vwe1FhwrRw+6q1k8wa9rWj+2afc9Oesp20JYbtVsy+/XXX38dvXs3evVqNoZSh2ppT4hCm//zAewu",
	"QFYAZ0Rp0x8cB//529Hob5++PLsZ2R9Pqx9/8l35fygcXODu27OuZr/y2OAAbkW7HRnbgw/9HFtrt69a",
	"an8p4AGRtVi1PWf8HVC3IsNgEhdptT6je1JUj7kNVe8jAeAthuQrU18/E+5KPT2YtOmPqJpVqgbRtSyR",
	"1MybNmls86ZFKe+DE/q7Dee/hhxFso0VRJlX6OuSpT/D1qr4/v0KWQtQj3gVLR6kaBVboNqH+7MsqenW",
	"YoPDgtY9JM5yD4lfxPEhBevwe2PtCv433U+J/IOKcMmv2wnbUanuCwF9abOz2u6qCcVHipo8TEoYXaBU",
	"ZaLnD5qZotYZiS7JkrLlBUMSrWyvMXyUNi9m0youoWLOP5kd4T9LKC6BXLD6dae+HErn9sr3qmp67oB4",
	"VI67DVPefXlQKidvAt/LfNLcfJzUTjJ7+e4dUdEKpeYYd1nRVvFfPgeJCDM7zFSZG5T23qG5+WhYk8do",
	"2HImuXAvuYhRmG2mzp69Gak3CeEL+czdya/4zJl/1MaSBn/DqXGTtH9sLvYd0lyAfUBBqYUaBMo8UbIe",
	"vTyI02sO/G6YY9miKT1lEY6tsmPPY8ZUZgnZgOYELUPupk6fIHx0aZ97EYPvhbPah/l9ytlcPmvw2ANk",
	"r3ZSr8FcVS3abQH0R3d5aC9zW/u43J0Tsna/q4+OD9GnJ4U3X9Ta6ATOlrhtWk4a9fC8CsN+/7H2ZcT5",
	"xlN0GE6JlBds729AApHlZyUvWGTm8h7LptIw18taCbjbc1l4+P0Dz6c0v6G9e9n4QOe479ucVIJEZT88",
	"ShgvazcDXlNZ6rAHIAMmI0jaIa3czf92R2N3ysjuyxxYtf1DxpofmcWpI4eHBP35g0Nh+fC5g+Y3ev7v",
	"ZA7e7KClV5x27flpepUbnd+bIv+e/MpqN/ir91vuXx0btqi2jOebwVzUjf/9PHTbwwH7cdD3vGfXvmnf",
	"59MWu/gPkI0K0Lfyjy1gfVXQ31x0DSYko5OrJ4YCrkd5G9SdTdG0dE/M3Z/a/4IJa4/sdLUHLkKqPakO",
	"HtYeuqM/N59u/jcAAP//EPH6vYx/AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
