// Centralized Hugeicons mapping for the home page.
// Reference design uses 27 hand-drawn 1.7-stroke SVGs; we map each to the
// closest Hugeicons free icon and render at strokeWidth 1.5 for visual parity.

export {
    Add01Icon as PlusIcon,
    ArrowDown01Icon as ChevronDownIcon,
    ArrowLeft01Icon as ChevronLeftIcon,
    ArrowRight01Icon as ChevronRightIcon,
    ArrowUpRight01Icon as ExternalLinkIcon,
    Bookmark02Icon as BookmarkIcon,
    BookOpen01Icon as MangaIcon,
    Calendar03Icon as CalendarIcon,
    Cancel01Icon as CloseIcon,
    ClipboardPasteIcon as PasteIcon,
    Clock01Icon as ClockIcon,
    Comment01Icon as CommentIcon,
    Copy01Icon as CopyIcon,
    Delete02Icon as DeleteIcon,
    Download04Icon as DownloadIcon,
    FavouriteIcon as HeartIcon,
    FilterIcon,
    FireIcon,
    Folder01Icon as FolderIcon,
    GridViewIcon as GridIcon,
    Home09Icon as HomeIcon,
    Image01Icon as ImageIcon,
    Layers01Icon as PagesIcon,
    Loading03Icon as LoaderIcon,
    MagnetIcon,
    Medal01Icon as RankIcon,
    MoreVerticalIcon as MoreIcon,
    PauseIcon,
    RedoDotIcon,
    RefreshIcon,
    Search01Icon as SearchIcon,
    Settings03Icon as SettingsIcon,
    SparklesIcon as AiIcon,
    SystemUpdate01Icon as SystemUpdateIcon,
    Tag01Icon as TagIcon,
    Tick02Icon as CheckIcon,
    UserMultiple03Icon as FollowIcon,
    ViewIcon as ViewsIcon,
    ZoomInAreaIcon as ZoomIcon,
} from "@hugeicons/core-free-icons";
